// Editorial examples describe conditional repair decisions, never local project claims.
// Each row: district, part, general intake, general acceptance, print preparation,
// print acceptance, scan capture, scan limitation, CAD references, CAD validation.
export const cases = [
['adalar','pil yuvası kapağı',
'Pil bölmesini kapatan plastik kapak eksikse önce pil tipi, kapanma yönü ve gövdede kalan yuvalar belgelenir. Kapak üzerindeki kilit, pilin temasını sağlayan metal parçadan ayrı değerlendirilir.',
'Yeni kapağın kabulü yalnızca dış görünüşe bağlanmaz. Kapatırken pil sıkışmamalı, açma çıkıntısına erişilebilmeli ve kapak normal kullanımda kendiliğinden ayrılmamalıdır; bu kontroller cihaz üzerinde yapılır.',
'Baskıya gönderilen pil kapağı dosyasında tırnak kökünü ve esneyen dili işaretleyin. İmalat yönü, kilidin hareketi ve görünen dış yüzey birlikte değerlendirilmeden yalnızca renk seçerek sipariş kesinleştirilmez.',
'İlk üretilen örnek enerjisi kesilmiş cihazın boş bölmesinde kontrol edilir. Mandalın kapanması, açma kuvveti ve köşelerdeki açıklık ayrı kaydedilir; pil takılı inceleme cihazın güvenli kullanım talimatına bağlıdır.',
'Sağlam eş kapak varsa içteki kilit diliyle dış kabuğu farklı açılardan gösterin. Bölme ağız geometrisi de referansa eklenir; yalnızca kapağın üst yüzeyini sayısallaştırmak kapanma ilişkisini açıklamaz.',
'Derin pil kanalı veya kilidin arkasında kalan dar yüzey taramada görünmeyebilir. Bu alanların ölçü ihtiyacı ayrıca yazılır; taranamayan yuvaya tahmini bir ölçü atayarak üretim dosyası hazırlanmaz.',
'Çizim başlangıcında kapak çevresi için gövde oturma düzlemi, kilit için yuva merkezi referans alınır. Dekoratif yüzeyi yeniden tasarlamadan önce açma hareketinin ve takma sırasının krokisi hazırlanır.',
'CAD tesliminde kilitli ve açık konumun ilişkisi kontrol edilir. Baskı modeliyle düzenlenebilir çalışma dosyasının kapsamı ayrı yazılır; pil sıkıştıran tasarım değişiklikleri işlevsel iyileştirme olarak kabul edilmez.'],
['arnavutkoy','kumanda düğmesi',
'Kaybolan kumanda düğmesinde milin dairesel, yassı veya kanallı olması belirleyicidir. Önden çekilmiş düğme fotoğrafına ek olarak mil kesiti, çevredeki panel ve dönme aralığı gösterilir.',
'Değerlendirme sonunda düğmenin konum işareti, kavrama rahatlığı ve panelden uzaklığı birlikte kararlaştırılır. İç bağlantı boşluğu nedeniyle işaret kayıyorsa dış görünüş tamamlanmış olsa bile numune kabul edilmez.',
'Düğme baskısında mil yuvasının ağzı ve ince gösterge çizgisi aynı kalite gereksinimine sahip değildir. Kritik iç yüzeyin korunması, yüzey temizliği ve görünüş beklentisi teklif kapsamına ayrı girer.',
'Üretilen düğme zorlanmadan takılmalı ve tanımlanmış dönme konumlarında paneli çizmemelidir. Mil üzerinde kayma ya da sökme sırasında gövdeyi çekme görülürse doğrudan adetli üretime geçilmez.',
'Tarama için eski düğmenin iç yuvasındaki kir, hasar ve aşınmayı fotoğrafta belirtin. Dış kavrama biçimi yakalanabilse de mil bağlantısı için karşı parçanın ölçüsü gerekebilir.',
'Parlak gösterge plakası veya derin mil deliği aynı veri kalitesini vermeyebilir. Yüzey işlemi gerekip gerekmediği numune korunma şartıyla konuşulur; renkli tarama ile birebir renk eşleştirme vaat edilmez.',
'Modellemede öncelik mil ekseni, düğme sıfır konumu ve panel açıklığıdır. Parmak girintileri sonradan ele alınır; farklı mil biçimindeki ürünler yalnızca dış çapları aynı diye tek modelde birleştirilmez.',
'Düzenlenebilir modelde mil kesiti ile gösterge yönü birbirine bağlı tutulur. Teslim incelemesi, işaretin gerçek cihaz konumuyla eşleşmesini ve komşu düğmeler arasında gerekli erişimin kalmasını kapsar.'],
['atasehir','dolap kapağı tutucu klipsi',
'Dolap kapağı tutucusu kırıldıysa kapak menteşesi, klips yatağı ve karşılık yüzeyi birlikte incelenir. Ağır kapağı taşımayan bir tutucu ile yük taşıyan menteşe elemanı aynı parça sınıfında değerlendirilmez.',
'Örnek tutucuda beklenen davranış kapağın kapalı konumda tutulmasıdır. Kapak hizası bozuksa bunu daha sert klipsle zorla telafi etmek yerine karşılıklı konumlar kontrol edilir ve montaj sorunu ayrılır.',
'Klips üretim dosyasında esneme kolunun kökü, vida deliği ve oturma tabanı gösterilir. İnce dilin baskı yönü ile sökülüp takılma hareketi birlikte ele alınır; yalnızca doluluk oranı çözüm sayılmaz.',
'İlk baskı kapağın yüksüz hareketinde denenir. Dil kökünde beyazlama, tabanın kalkması veya kapağın gereğinden fazla zorlanması revizyon nedenidir; deneme gözlemleri üretim adedinden önce paylaşılır.',
'Kırılmış klipsin bütün parçaları yanında sağlam karşılık da tarama referansına eklenebilir. Birleşme hattındaki eksik malzemeyi orijinal tasarım yüzeyi sanmamak için hasar alanını ayrıca işaretleyin.',
'Esnek klips ölçüm sırasında bükülü tutulursa yanlış konum kaydedilebilir. Serbest haliyle takılı durum arasındaki fark fotoğraflanır; tek tarama bu iki durumu kendiliğinden ayıramaz.',
'Klips çiziminde sabit montaj tabanı ile hareket eden dil ayrı işlevlerle tanımlanır. Karşılık yüzeyinin giriş eğimi ve kapalı konum, yalnızca eski parçanın kırık ucuna bakılarak tahmin edilmez.',
'Model revizyonu sonrasında vida oturma noktası korunurken dilin erişimi ayrıca kontrol edilir. Değiştirilen her ölçünün kapak kapanmasına etkisi not edilir; kontrolsüz kalınlaştırma başarılı tasarım ölçütü değildir.'],
['avcilar','çekmece rayı sonlandırıcısı',
'Çekmece rayının ucundaki plastik durdurucu eksikse ray profili ve sağlam diğer uç karşılaştırılır. Çekmecenin yükünü taşıyan kilit veya düşmeyi önleyen güvenlik işlevi varsa kapsam ayrıca incelenir.',
'Talepte çekmecenin hangi noktada durması gerektiği ve parçanın ray içinde nasıl sabitlendiği açıklanır. Sonlandırıcının yerinde kalması ile çekmecenin güvenle taşınması aynı kabul kontrolü olarak birleştirilmez.',
'Sonlandırıcının baskısında raya giren ayak ile çarpma yüzeyi farklı iş görür. Dosyadaki boşluklar, kenar yumuşatmaları ve montaj yönü kontrol edilerek ilk numunenin denenme şekli belirlenir.',
'Deneme rayı yüksüz durumda elle hareket ettirerek başlar. Sürtme, durma noktası ve plastik gövdenin yer değiştirmesi kaydedilir; ilk uyum, kullanım ömrü veya taşıma kapasitesi doğrulaması sayılmaz.',
'Tarama referansı mümkünse sağlam karşı sonlandırıcı ve rayın uç bölümünü kapsar. Sağ-sol aynalama yapılacaksa vida ve kanca düzeninin gerçekten simetrik olup olmadığı ayrıca fotoğraflarla gösterilir.',
'Rayın içinde kalan kilit dudağı optik olarak görünmüyorsa tarama dış biçimi verir. İç kilidin değerlendirmesi için erişilebilir kesit veya doğrudan ölçü gerekir; görüntü boşluğu rastgele kapatılmaz.',
'CAD çalışmasında ray kesiti ana referanstır; dış kabuğun estetiği son sırada ele alınır. Durdurma yüzeyinin yeri çekmecenin gerçek hareket mesafesine göre tanımlanır ve montaj yönü dosyada belirtilir.',
'Teslim edilen modelin sağ ve sol varyantları açıkça kodlanır. Görünüşte benzer iki uçta ters kanca kullanılması ihtimali, simetri varsayımına güvenmek yerine ray üzerinde karşılaştırılarak sonuçlandırılır.'],
['bagcilar','elektrik süpürgesi uç adaptörü',
'Süpürge borusuyla mevcut başlık uyuşmuyorsa iki bağlantının iç ve dış çaplarını, giriş derinliğini ve kilit biçimini ayrı kaydedin. Hava yolu adaptörü, elektrik bağlantılı başlık ara elemanından ayrılır.',
'Adaptörde amaç yalnızca iki parçayı birleştirmek değildir. Başlığın yön değiştirmesi, borunun sökülebilmesi ve hava yolunun gereksiz daralmaması birlikte kontrol edilir; elektrikli bağlantı için doğrulanmamış ara parça önerilmez.',
'Baskı planında ince boru ağzı, varsa kilit deliği ve gövde geçişi işaretlenir. Destek temizliğinin iç hava kanalını daraltmaması gerekir; malzeme kararı ortam ve kullanım bilgisiyle birlikte verilir.',
'Numune iki uçta da ayrı denenir ve ardından birleşik uzunluğun kullanım rahatlığına etkisi değerlendirilir. Sıkı geçen parçayı zorlayarak takmak, doğru ölçü alınmış bağlantının yerine kabul ölçütü olamaz.',
'Tarama öncesinde boru ve başlığın bağlantı yüzeylerini ayrı fotoğraflayın. Dairesel görünen ağız ovalleşmiş olabilir; kilit yönüyle geometrik merkez arasındaki ilişki dosya kapsamına dahil edilir.',
'Uzun ve dar kanalın tamamı dışarıdan yakalanamayabilir. Adaptörün işlevi için gereken giriş bölgesiyle cihazın iç yapısını ayırmak, gereksiz veri toplamayı ve eksik yüzeyi yanlış yorumlamayı önler.',
'Adaptör modelinde iki bağlantı ekseni ve toplam erişim uzunluğu başlangıç girdileridir. Geçiş duvarı, kilit açıklığı ve ayrılma tutamağı birbirine çarpışmadan çalışacak şekilde değerlendirilir.',
'Çizim tesliminde her ucun hangi mevcut parçaya ait olduğu isimlendirilir. Kontrol, takma derinliği ve sökme erişimini kapsar; dosyanın kapalı bir katı olması tek başına kullanılabilirlik onayı değildir.'],
['bahcelievler','perde kumanda zinciri bağlantısı',
'Perde zincirindeki bağlantı parçası kayıpsa zincir adımı ve mevcut mekanizmanın geçiş aralığı birlikte incelenir. Çocuk güvenliği ya da koparak ayrılma işlevi olan bağlantının sıradan klips gibi çoğaltılması uygun kabul edilmez.',
'Ön değerlendirme bağlantının görevinin tanımlanmasıyla sonuçlanır. Parça güvenlik düzeninin elemanıysa üreticiye uygun çözüm aranır; işlevi belirsiz parçaya daha güçlü bir kopya yapmak iyileştirme olarak sunulmaz.',
'Yalnızca uygunluğu belirlenen güvenlik dışı zincir kılavuzu için baskı konuşulur. Kanalın geçiş açıklığı, kenar pürüzü ve bağlantı yönü dosyada belirtilir; güvenlik kopma kuvveti bilinmeden üretim taahhüdü verilmez.',
'Baskı numunesinde zincir yüksüz hareket ettirilerek sürtme ve takılma izlenir. Serbest hareket gözlemi, çocuk güvenliği veya kopma düzeninin sertifikası olarak değerlendirilmez; görev sınırı teslim notunda kalır.',
'Tarama talebinde parçanın mekanizmaya takılı görüntüsünü de verin. Zincir kılavuzu ile ayrılabilir emniyet bağlantısının biçimce benzemesi mümkündür; hangi işlevin belgeleneceği baştan netleştirilir.',
'Küçük küresel zincir yuvaları yüzey verisinde birleşmiş görünebilir. Zincir adımı ve yuva biçimi ayrıca ölçülmeden bu veri yeniden üretime hazır referans olarak sınıflandırılmaz.',
'Modelleme kapsamı güvenlik dışı kapak veya kılavuzla sınırlandırıldığında zincirin hareket hacmi çizilir. Tasarım, mekanizmanın koruyucu düzenini devre dışı bırakacak sürekli bir köprüye dönüştürülmez.',
'Teslim incelemesinde hareket yolunun açıklığı ve montaj erişimi kontrol edilir. Çizime eklenen işlev notu, parçanın emniyet bağlantısı yerine kullanılamayacağını açıklar; bilinmeyen kopma davranışı tasarlanmış gibi gösterilmez.'],
['bakirkoy','masa lambası dış düğme kapağı',
'Lambanın dış düğme kapağı kırıldığında kullanıcıya dokunan plastikle elektriksel yalıtım elemanını ayırın. Anahtarın enerjisiz görüntüsü, mil biçimi ve kapak altında görünen açıklık talebin temel girdileridir.',
'İnceleme, üretilecek dış kapağın anahtara erişimi ve kullanım hareketini koruyup korumadığını belirler. Isı veya elektrik güvenliği işlevi taşıyan gövdeler için görünüşe dayalı eşdeğerlik iddiası kurulmaz.',
'Dış kapak baskısında mil deliği, parmak temas yüzeyi ve panel açıklığı birlikte değerlendirilir. Isı kaynağına yakınlık bilgisi alınmadan herhangi bir baskı malzemesi lambaya uygun ilan edilmez.',
'Uyum kontrolü enerjisiz üründe yapılır; kapak takıldığında anahtar sıkışmamalı ve gövdeye sürtmemelidir. Elektrikli kullanımın uygunluğu, bu mekanik denemeden ayrı bir sorumluluk ve değerlendirme konusudur.',
'Tarama için kapak sökülebiliyorsa yalnızca yetkin biçimde güvenle ayrılmış numune kabul edilir. Dış desen kadar mil yatağının yönü ve cihaz paneline bakan oturma yüzeyi de referans olmalıdır.',
'Parçanın içinde görünmeyen yalıtım katmanları tarama görüntüsünden çıkarılamaz. Tarama raporu geometri kapsamını belirtir; elektriksel malzeme özellikleri ölçülmüş gibi bir dosya açıklaması eklenmez.',
'Modelleme önce mil bağlantısı ile dış erişim alanını çözer. Kapağın büyütülmesi anahtarı daha rahat kullanılır kılabilir, ancak çevredeki koruyucu açıklıkları veya cihazın havalandırmasını kapatmamalıdır.',
'Model revizyonunda dış profil ile cihaz açıklığı çakıştırılarak sürtme riski incelenir. Teslim edilen tasarımın işlevi dış kumanda kapağı olarak adlandırılır; yalıtım standardını karşıladığına dair belgesiz beyan yazılmaz.'],
['basaksehir','sandalye borusu uç tapası',
'Sandalye ayağındaki tapa eksikse boru kesiti, duvarı ve zemine basma yönü kaydedilir. Sessizlik veya zemini koruma beklentisi ile yapısal taşıma işlevi farklı gereksinimler olarak belirtilmelidir.',
'Tapanın yuvada tutulması, zemine dengeli oturması ve keskin boru ucunu kapatması ilk değerlendirmeye girer. Sandalyenin taşıma güvenliği yeni bir tapayla otomatik olarak doğrulanmış sayılmaz.',
'Baskıya hazırlıkta boruya giren kanatçıklar ve zemine bakan taban incelenir. Zeminin türü ve temizleme koşulları paylaşılmadan her yüzeyde kaymazlık veya çizmezlik iddiası kurulmaz.',
'İlk örnekte boruya giriş, eğimli tabanın yönü ve zemindeki iz gözlemlenir. Uygunluğu değerlendirilmemiş tapayla yüklü sandalye denemesi yapılmaz; mekanik tutunma ile yüzey davranışı ayrı kaydedilir.',
'Sağlam eş tapa taranacaksa aşınmış basma yüzeyi özellikle belirtilir. Borunun iç kesiti ve açısı da ölçü referansına girer; aşınmayı aynı biçimde kopyalamak hedef olarak kabul edilmez.',
'İnce kanatçıkların birbirine değmesi veya yumuşak parçanın tutulurken şekil değiştirmesi veri kalitesini etkiler. Tarama konumu kaydedilir ve ölçünün serbest halde mi montajdayken mi alındığı ayrılır.',
'CAD modelinde boru içine oturan bölümle zemin temas düzlemi birbirine göre konumlandırılır. Boru eğikse tabanı gelişigüzel kalınlaştırmak yerine gerçek duruşa uygun geometrik ilişki kurulur.',
'Dosyada sandalye ayağının sağ-sol ya da ön-arka varyantı belirtilir. Basma açısı farklı ayaklar tek tip tapayla birleştirilmeden önce kontrol edilir; çizimdeki simetri ürünün simetrisi sanılmaz.'],
['bayrampasa','oyuncak gövdesi dekoratif kapağı',
'Oyuncak üzerindeki dekoratif kapak için çocuğun yaş grubu, kırılma yeri ve parçanın kopabilirliği baştan yazılmalıdır. Yeni küçük plastik parça üretmek, oyuncak güvenliği şartlarını sağladığı anlamına gelmez.',
'İlk karar parçanın kullanım yerine uygun biçimde değerlendirilebilip değerlendirilemeyeceğidir. Ağıza alınan, yiyecekle temas eden veya küçük parça riski taşıyan bileşenlerde yalnızca ölçü uyumu yeterli kabul edilmez.',
'Dekoratif kapağın üretimi değerlendirilecekse ince sivri uçlar, ayrılabilir süsler ve montaj bağlantıları dosyada gösterilir. Malzemenin rengi veya baskı kalitesi, oyuncak kullanımına uygunluk belgesinin yerine geçmez.',
'Üretilen örnek çocuğun kullanımına verilmeden önce sorumlu kişi tarafından kapsamına uygun incelenir. Montaj kontrolü veya dış yüzey incelemesi, tamamlanmamış ürün güvenliği değerlendirmesini kapatmış sayılmaz.',
'Tarama çalışması oyuncak kapağını dijital arşivlemek için de yapılabilir; bu hedef yeniden kullanım hedefinden ayrılır. Gövde kırıkları ve sonradan yapıştırılan alanlar referans kaydında işaretlenir.',
'Yumuşak dekoratif parça sabitlenirken esnerse kayıt özgün formu temsil etmeyebilir. Parçanın serbest duruşu fotoğraflanır; doku ve renk verisi mekanik veya kimyasal güvenlik bilgisi olarak yorumlanmaz.',
'Kapak modellemesinde erişilebilir kenarlar ve küçük ayrılabilir elemanlar açıkça tanımlanır. Tasarım yalnızca sergileme veya yetişkin koleksiyonu içinse bu kullanım sınırı proje açıklamasında belirtilir.',
'Teslim kapsamı dijital model, sergileme örneği veya değerlendirme numunesi olarak ayrılır. Üretici onayı ve uygunluk incelemesi bulunmayan bir çizimin çocuk kullanımına hazır olduğu söylenmez.'],
['besiktas','kulaklık menteşe dış kapağı',
'Kulaklıkta kırılan parça menteşenin dış kapağı mı yoksa taşıyıcı eklem mi, önce bu ayrım yapılır. Kablo geçişi, döndürme açısı ve sağlam karşı taraf görüntüsü değerlendirmeyi destekler.',
'Dış kapağın kapanması kadar kablonun sıkışmaması ve kulaklığın katlanabilmesi de önemlidir. Taşıyıcı menteşe arızası kapakla örtülerek onarılmış kabul edilmez; hangi işlevin değişeceği yazılır.',
'Baskı dosyasında ince vida ayakları ile dış görünüş yüzeyi ayrılır. Kablo kanalı için bırakılan açıklık, destek temizliği sonrasında korunmalıdır; sertleşen bir kapak esneme ihtiyacını tek başına çözmez.',
'Numune kulaklığın kapalı, açık ve normal kullanım konumlarında yüksüz kontrol edilir. Kabloya temas, vida çevresinde çatlama ya da menteşe hareketinde azalma görülürse kayıtla birlikte revizyon istenir.',
'Tarama için kulaklığın sağlam tarafı kullanılacaksa aynalanacak ve aynalanmayacak ayrıntılar gösterilir. Kablo girişi veya düğme yönü iki tarafta farklı olabilir; geometrik simetri otomatik varsayılmaz.',
'Kapak altındaki kablo yuvası tarama hattından saklanabilir. Dış kabuk verisine dayanarak görünmeyen iç boşluklar kapatılmaz; sökülebilen güvenli numune veya tamamlayıcı ölçü ihtiyacı ayrıca belirlenir.',
'CAD düzeninde menteşe ekseni ve kablo geçiş hacmi sabit referans alınır. Vida ayaklarının yeri belirlendikten sonra dış kontur düzenlenir; kapak kalınlığı artırılırken dönme alanı daraltılmamalıdır.',
'Teslim kontrolü, karşı taraftan alınan formun doğru tarafa uyarlanmasını ve vida uzunluğu bilgisinin korunmasını içerir. Kapak ile taşıyıcı eklem farklı parça kodlarıyla tanımlanır.'],
['beykoz','bahçe hortumu kılavuz halkası',
'Hortumu düzenleyen bir kılavuz halkanın iç çapı, sabitlenme biçimi ve hortumun bükülme yönü bilinmelidir. Basınç altında sızdırmazlık sağlayan bağlantı elemanları bu basit yönlendirme örneğinden ayrı değerlendirilir.',
'Kılavuzun kabulü hortumu ezmeden yönlendirmesi ve çevrede keskin temas oluşturmamasına dayanır. Doğrudan güneş, su ve temizleyici maruziyeti yazılır; açık hava kullanım ömrü tahmin edilerek taahhüt edilmez.',
'Baskı planında halka ağzının açıklığı ve sabitleme ayağının yük yönü gösterilir. Hortumun sürtündüğü yüzeyde destek izlerinin kalmaması hedefi belirtilir; sızdırmaz basınç bağlantısı üretimiyle karıştırılmaz.',
'Deneme halkanın montaj yerinde hortum boşken geçiş kontrolüyle başlar. Sıkışma ve sürtme izleri kaydedilir; bu kontrol basınç, su geçirimsizlik veya dış ortam dayanım testi olarak raporlanmaz.',
'Tarama referansı kırık halkayla sınırlı kalmamalıdır; sabitlendiği yüzey ve hortumun geçtiği yol gösterilir. Yıpranmış temas kenarları, korunacak tasarımdan farklı renkle fotoğrafta işaretlenebilir.',
'Şeffaf veya ıslak yüzey veri alımını etkileyebilir. Hazırlık yöntemi numunenin zarar görmemesi koşuluyla belirlenir; taramanın suya dayanım özelliğini ölçtüğü yönünde bir sonuç çıkarılmaz.',
'Modelde halka açıklığı, hortum dış çapı ve dönüşte gereken boşluk ilişkilendirilir. Sabitleme ayağı mevcut delikleri kullanacaksa delik düzeni doğrulanır; zemine yeni bağlantı gereksinimi gizlenmez.',
'CAD tesliminde kapalı halka ile sonradan takılabilir açık kılavuz alternatifleri işlevleriyle ayrılır. Montaj kolaylığı tercih edilirken hortumun halkadan çıkma olasılığı da değerlendirme notuna eklenir.'],
['beylikduzu','kablo kanalı uç kapağı',
'Kablo kanalındaki uç kapak kayıpsa kanal kesiti ve kapak dudakları fotoğraflanır. Parçanın yalnızca dekoratif kapama mı yoksa elektriksel koruyucu muhafaza mı olduğu yetkin değerlendirmeyle ayrılmalıdır.',
'Görünür boşluğun kapanması tek kabul ölçütü değildir. Kablo sıkışması, keskin uç ve erişim ihtiyacı kontrol edilir; elektrik tesisatına ait uygunluk sorumluluğu baskı geometrisinden bağımsız ele alınır.',
'Uç kapağı üretiminde iç oturma dudağı ve kanal kapağıyla birleşme çizgisi dosyada gösterilir. Malzeme seçimi yapılırken alev davranışı gibi belgelenmemiş özellikler varsayılarak ürün uygunluğu ilan edilmez.',
'Mekanik numune kanalla enerjisiz ve uygun koşulda eşleştirilir. Tırnakların oturması, kapağın sökülebilmesi ve kablo geçişinin ezilmemesi kaydedilir; elektrikli sistemde kullanım yetkin incelemeye bağlıdır.',
'Tarama için kanalın kısa bir örneği veya erişilebilir açık kesiti faydalıdır. Uç kapağın dış görüntüsü, kanal içine giren kancaların yönünü tek başına açıklamaz; iç yüzey kapsamı baştan yazılır.',
'Uzun kanalın tamamını sayısallaştırmak her zaman gerekli değildir. Talep uç kapamaysa bağlantı kesitinin yeterliliği değerlendirilir; duvar içindeki veya kapalı bölümdeki kablolar görüntülenmiş gibi gösterilmez.',
'CAD çalışmasında kanal profilinin iç ve dış kenarları ayrı referanslanır. Dekoratif alın yüzeyi çizilirken kapağın tırnakla tutunma payı ve mevcut kanal kapağının açılma sırası korunur.',
'Dosya tesliminde uç kapama yönü, varsa sağ-sol ayrımı ve erişim açıklığı işaretlenir. Çizimin uygun bulunması kanal sisteminin elektriksel ya da yangın güvenliği onayı yerine geçmez.'],
['beyoglu','çanta fermuar çekme ucu',
'Çanta fermuarının yalnızca çekme ucu eksikse sürgü gövdesi ve bağlantı halkası incelenir. Sürgü dişleri tutmuyorsa yeni tutamak yapmak asıl mekanik arızayı gidermez; talep bu ayrımla başlar.',
'Tutamakta parmak kavrayışı, hareket yönü ve kumaşa temas eden kenarlar kabul başlıklarıdır. Ağır yük taşımak için kullanılan askı kancası ile fermuar çekme parçası aynı dayanım beklentisiyle ele alınmaz.',
'Çekme ucu baskısında bağlantı deliğinin kenarı ve kavrama gövdesi incelenir. Sonradan takılacak halka veya pim ayrıca tarif edilmelidir; montaj donanımının baskıya kendiliğinden dahil olduğu varsayılmaz.',
'İlk örnek fermuarın tüm yolunda nazikçe hareket ettirilir. Kumaşa takılma, sürgü açısının bozulması ve parmağı rahatsız eden çıkıntı kaydedilir; kontrol bir kopma dayanımı sertifikası oluşturmaz.',
'Tarama talebinde sağlam eş çekme ucu kadar sürgünün bağlantı halkası da belgelenir. Küçük deliğin iç duvarı görünmüyorsa dış siluet tek başına üretim ölçüsü olarak kullanılmaz.',
'Eski tutamaktaki esnek kayış veya kumaş parça sabit bir geometri sunmayabilir. Metal halka, plastik gövde ve yumuşak bölüm ayrı referanslar olarak tanımlanır; tek malzemeli tarama modeliyle eşdeğer sayılmaz.',
'Modelleme tutamağın ele gelişini ve sürgüye bağlanmasını birlikte çözer. Büyük dekoratif uç seçilirse komşu ceplerle çarpışma ve çantayı kapatırken sıkışma olasılığı çizim üzerinde değerlendirilir.',
'Dijital teslimde bağlantı halkasının mevcut ölçüsü ve tutamağın önerilen formu ayrılır. Onay, yalnızca render görüntüsüne değil gerçek sürgü üzerinde yapılacak erişim ve hareket kontrolüne bağlanır.'],
['buyukcekmece','valiz teleskopik kol dış çerçevesi',
'Valiz kolunun dış çerçevesi kırıldığında taşıyıcı teleskopik borular ve kilit mekanizması ayrıca incelenmelidir. Plastik çevre kapaması ile yük taşıyan tutamak aynı onarım kapsamına alınmaz.',
'İlk karar, kırığın kol hareketini engelleyip engellemediğidir. Çerçeve yerine otursa bile kilit pimi çalışmıyorsa valiz onarılmış sayılmaz; dış parçanın sınırı ve mekanizmanın durumu ayrı kaydedilir.',
'Çerçeve baskısında vida yuvaları, boru geçişleri ve köşe açıklıkları dosyada belirtilir. Kasa eğilmişse yeni parçayı zorla oturtmak yerine mevcut montaj ölçüleri yeniden kontrol edilir.',
'Baskı örneği yük taşımadan kolun kapanıp açılmasıyla incelenir. Boruya sürtme, kilit düğmesine erişim ve gövdeyle birleşme kontrol edilir; taşıma yükünü doğrulayan bir sonuç çıkarılmaz.',
'Tarama sırasında valiz kolu kapalı ve açık konumlarda fotoğraflanır. Sayısallaştırılacak dış çerçeve ile hareket eden boruların referansları ayrılır; farklı konumlar yanlışlıkla tek yüzeyde birleştirilmez.',
'Çerçevenin kasa içinde kalan vida ayakları erişilemeyebilir. Sökme durumu güvenle değerlendirilmeden yalnızca dış taramayla tam bağlantı geometrisi çıkarıldığı söylenmez; gizli yüzeyler ayrıca listelenir.',
'CAD tasarımında boruların paralelliği ve kasadaki vida düzeni önce çözülür. Dış köşeler düzenlenirken kolun kapanma hareketine gereken açıklık korunur; taşıyıcı mekanizma belgesiz biçimde yeniden tasarlanmaz.',
'Model teslimi çerçeveye ait parça sınırını açık gösterir. Vida ayakları ve geçişler montaj bilgisiyle karşılaştırılır; valizin taşıma güvenliği bu dış kapama modelinin kabul kriterine indirgenmez.'],
['catalca','alet kutusu bölme ayırıcı',
'Alet kutusunda eksik ayırıcı için kutu tabanı, kapak kapanma yüksekliği ve bölme kanalları ölçülür. Kesici alet, ağır parça veya sıvı taşıma ihtiyacı varsa bölmenin görevi açıkça belirtilmelidir.',
'Ayırıcının beklenen sonucu eşyaların belirlenen bölmelerde kalmasıdır. Kutu kapağını yukarı iten, çıkarılırken kırılan ya da taşıma sırasında yerinden çıkan tasarım yalnızca görsel uyumla kabul edilmez.',
'Bölme baskısında uzun ince duvarların doğruluğu ve kutuya giren taban ayakları dikkate alınır. Duvarı gereksiz kalınlaştırmak hacmi azaltabilir; adetli baskıdan önce tek bölme üzerinde uyum görülür.',
'Numune boş kutuda oturtulur, ardından tanımlı eşyaların sığması kontrol edilir. Kapak kapandığında ayırıcıya baskı olup olmadığı kaydedilir; taşınacak ağırlık için verilmemiş bir kapasite değeri eklenmez.',
'Tarama için kutunun iç tabanı ve ayırıcı kanalları önceliklidir. Dış kapağın ayrıntıları her zaman gerekli değildir; hangi bölme sınırlarının dijital kayda alınacağı fotoğraf üzerinde işaretlenir.',
'Derin kutunun köşeleri görüş hattını kısıtlayabilir. Erişilemeyen taban bölgeleri tamamlayıcı ölçüyle ele alınır; boşluk doldurularak üretilen yüzey gerçek ölçülmüş taban gibi sunulmaz.',
'CAD modelinde kutu iç hacmi içinde ayırıcının yerleşim düzeni kurulabilir. Farklı eşyalar için bölme seçenekleri hazırlanacaksa her alternatifin konumu ve kapak yüksekliğiyle ilişkisi açıkça ayrılır.',
'Teslim kontrolü, çıkarılabilir bölmelerin elle erişimini ve taban kanallarına oturmasını kapsar. Ayırıcı kodları yerleşim krokisiyle eşleşir; boş kutu hacmi ile kullanılabilir bölüm hacmi karıştırılmaz.'],
['cekmekoy','mobilya kablo geçiş bileziği',
'Masa üzerindeki kablo deliği için bilezik isteniyorsa delik çapı, tabla kalınlığı ve kablo fişlerinin geçiş ihtiyacı kaydedilir. Sadece kablo çapını ölçmek takılı fişin geçip geçmeyeceğini açıklamaz.',
'Bileziğin masa kenarını kapatması ve kabloyu keskin yüzeyden ayırması beklenir. Açılır kapak gerekiyorsa kablolar takılıyken erişim incelenir; masa tablasındaki mevcut hasar yeni parçayla gizlenmiş sayılmaz.',
'Baskıda tablaya oturan dış flanş ile deliğe giren gövde ayrı yüzeylerdir. İnce üst kenarda eğilme ve iç geçişte çapak istemi not edilir; yüzey temizliği kapsamı siparişte belirtilir.',
'İlk örnek kablosuz olarak deliğe oturtulur, ardından gerçek fişlerin geçişi kontrol edilir. Flanşın kalkması veya tabla kaplamasını zedelemesi revizyon nedenidir; zorlayarak montaj uygunluk kanıtı değildir.',
'Tarama referansı için masa deliğinin kenarı ve alt yüzey erişimi önemlidir. Delik oval veya eğriyse tek çap değeri yeterli olmaz; mevcut form ile hedeflenen düzgün form birbirinden ayrılır.',
'Kablo yığını açıklığı örterse deliğin tamamı görülemeyebilir. Çalışma alanının güvenli biçimde boşaltılması ya da erişilebilir ölçülerle desteklenmesi konuşulur; kapalı kenarların ölçüldüğü varsayılmaz.',
'Modelleme bileziğin tabla kalınlığına uygun gövdesiyle başlar. Kablolar sökülmeden takılabilen iki parçalı çözüm düşünülüyorsa birleşme çizgisinin kablo sıkıştırmaması ayrıca değerlendirilir.',
'CAD tesliminde üst görünüş kadar masanın altına taşan bölüm de incelenir. Diz mesafesi, çekmece ve fişlerin geçiş hacmi korunur; yalnızca dış çapa göre tamamlandı kararı verilmez.'],
['esenler','vantilatör dış ayar düğmesi',
'Vantilatörün dış ayar düğmesi kayıpsa mil bağlantısı, konum göstergesi ve düğmenin çevresindeki gövde açıklığı kaydedilir. Pervane, koruyucu kafes ve elektriksel iç parçalar bu örnekten ayrı kapsamdır.',
'Değerlendirme düğmenin ayar konumunu doğru göstermesi ve rahatça sökülüp takılması üzerinde kurulur. Kontrol anahtarının kendi arızası varsa plastik düğme üretmek cihazı çalışır veya güvenli hale getirmez.',
'Düğme dosyasında mil deliğinin biçimi ve gösterge çizgisinin yönü kontrol edilir. Görsel yüzeye verilen kaplama, iç bağlantıyı daraltmamalıdır; son işlemin kritik ölçüye etkisi baştan belirtilir.',
'Baskı örneği enerji kesilmiş durumda ayar konumlarında kontrol edilir. Düğmenin dönüp milin dönmemesi veya göstergenin yanlış konuma gelmesi uygunsuzluktur; mekanik kontrol elektriksel kullanım onayı sayılmaz.',
'Tarama için sağlam düğmenin iç deliği ve gösterge noktası birlikte referanslanır. Mil uç yüzeyi de fotoğraflanır; yalnızca dış kavrama kanallarını almak bağlantı biçimini tanımlamak için yeterli değildir.',
'Dar mil yuvasının tabanı veya yassı kesiti görülemeyebilir. Optik kayıtta eksik kalan bağlantı bilgisi ayrıca ölçülür; cihaz çalıştırılarak elde edilen hareket tahmini geometrik ölçü yerine konmaz.',
'CAD çalışmasında gösterge ile mil yassı yüzeyi arasındaki açı temel parametredir. Kullanıcı tutuşunu değiştiren dış form alternatifleri bu yön ilişkisini bozmadan ayrı varyantlar halinde ele alınır.',
'Teslim edilen model, seçici anahtarın gerçek konum adlarıyla karşılaştırılır. Yanlış yönlendiren işaret düzeltilmeden üretim onayı verilmez; pervane ya da koruyucu parça tasarlandığına dair kapsam genişletilmez.'],
['esenyurt','mutfak çekmecesi düzenleyici bağlantısı',
'Çekmece içindeki düzenleyici bağlantısı kırıldıysa iki birleşen profilin kesiti ve hareket yönü gösterilir. Gıda temas eden parça ile yalnızca bölmeleri tutan dış bağlantı farklı kullanım şartları taşır.',
'Bağlantının kabulü bölmeleri yerinde tutması ve çekmecenin kapanmasına engel olmamasıyla değerlendirilir. Yıkama veya temizleyici kullanımı talepte belirtilir; bilinmeyen malzemeye gıda uygunluğu atfedilmez.',
'Baskı hazırlığında iki profilin kavrama yüzeyleri ve bağlantının sökme yönü ayrı gösterilir. İç köşelerde destek izi birikmesi montajı etkileyebilir; temizleme erişimi üretim planına dahil edilir.',
'Numune önce boş düzenleyicide birleştirilir, sonra çekmece hareketi izlenir. Bölmelerin eğilmesi veya çekmece yanına sürtmesi kaydedilir; gıda teması ve yıkama dayanımı bu uyum denemesinden çıkarılmaz.',
'Tarama için yalnızca bağlantı değil birleşen profillerin kısa örnekleri de referans olabilir. Uzun profilin doğruluğu ile küçük bağlantının yerel formu ayrı konulardır; uç kesitler özellikle belgelenir.',
'İç içe geçen yüzeyler montajdayken görünmeyebilir. Sökülemeyen birleşimde erişim sınırı yazılır; tarama meshinde kapanan boşluklar gerçek dolu malzeme olarak kabul edilmeden önce kontrol edilir.',
'CAD modelinde bağlantının tuttuğu iki profil ekseni ve tabla mesafesi tanımlanır. Düzenleyicinin yeniden dizilebilmesi isteniyorsa geçmenin sökülme sırası ve parmak erişimi de tasarım girdisi olur.',
'Çizim tesliminde farklı profil ölçüleri açık kodlanır. Aynı görünümlü fakat farklı kesitli düzenleyiciler tek modele bağlanmaz; temizlik için erişilebilir bölgeler montaj krokisinde gösterilir.'],
['eyupsultan','kavanoz dış taşıma sepeti klipsi',
'Kavanozları bir arada tutan dış sepet klipsi incelenirken camla temas eden yüzey ve klipsin yük taşıma görevi belirtilir. Kavanoz kapağı veya yiyecekle temas eden conta bu talebin yerine geçmez.',
'Ön karar klipsin yalnızca bölme ayırması mı yoksa sepeti taşırken ağırlığı tutması mı gerektiğidir. Taşıyıcı rol bilinmeden cam yükün altında deneme önerilmez; kabul planı işleve göre hazırlanır.',
'Uygunluğu değerlendirilen düzenleyici klips baskısında birleşme kancası ve camı karşılayan köşe incelenir. Sert bir köşenin doğrudan cama basmasını önleyecek temas tasarımı ayrıca konuşulur.',
'Numune camsız ve yüksüz sepet üzerinde denenir. Açılıp kapanma, kancanın yuvaya oturması ve çevredeki boşluk kontrol edilir; bu sonuç kırılabilir yükün taşınabileceği anlamına gelmez.',
'Tarama talebine sağlam sepet köşesi ve klipsin karşılık yuvası eklenir. Gevşek veya eğilmiş sepet, orijinal klips biçimini yanıltabilir; mevcut bozulmalar referans notunda açıklanır.',
'Şeffaf cam ile plastik klips aynı tarama girdisi değildir. Görev yalnızca klips geometrisiyse camın optik yüzeyinden ölçü çıkarma ihtiyacı ayrıca değerlendirilir ve varsayımla tamamlanmaz.',
'CAD modelinde klipsin tuttuğu sepet elemanlarının kesiti ve aralığı sabitlenir. Yük yolu bilinmiyorsa tasarım taşıma aparatı olarak adlandırılmaz; düzenleme veya sabitleme sınırı açık yazılır.',
'Teslim incelemesinde klipsin açılma yönü ve cama bakan temas yüzeyi görünür olmalıdır. Montaj görseli, parçanın kavanoz kapağı ya da sızdırmazlık bileşeni olmadığını da netleştirir.'],
['fatih','eski radyo ön panel düğmesi',
'Eski radyonun düğmesi eksikse özgün görünüş beklentisiyle işlevsel bağlantı ihtiyacı ayrı yazılır. Mil şekli, panel mesafesi ve sağlam düğmenin fotoğrafı korunacak tasarımı açıklamaya yardımcı olur.',
'Kabul planında gösterge hizası, paneli çizmeden dönme ve sökülebilirlik bulunur. Antika numunenin korunması öncelikliyse üzerine işaret, kaplama veya yapıştırıcı uygulanmasına ilişkin sınırlar baştan belirlenir.',
'Düğme baskısında dekoratif tırtıl ile mil bağlantısının boyutsal görevi farklıdır. Yüzey dokusunun görünüşü numuneyle konuşulur; fotoğraf üzerinden tarihî malzemeyle birebir eşdeğerlik vaat edilmez.',
'İlk örnek cihaz enerjisizken mile takılır ve panel aralığı kontrol edilir. Eski mil veya anahtar zarar görmesin diye zorlama yapılmaz; sıkışan bağlantı revizyon için ölçülü biçimde belgelenir.',
'Tarama sırasında özgün numunenin çatlakları ve eskime izleri ayrı kayda alınır. Amaç bunları koruyan arşiv modeli mi, hasarı giderilmiş yeniden yapım referansı mı, çalışma öncesinde seçilir.',
'Numuneye yüzey hazırlığı uygulanması gerekiyorsa korunma şartları değerlendirilir. Dijital kayıt alınması fiziksel parçanın rengini veya malzeme bileşimini belirlemez; yalnızca elde edilen veri türü teslimde yazılır.',
'CAD modellemede mil geometrisiyle panel referansı önceliklidir; dış süslemeler bundan sonra işlenir. Eksik dekoratif motif tahmin edilecekse bu bölüm ölçülen kısımlardan ayrı belirtilir.',
'Teslimde özgün tarama, düzenlenen model ve baskı dosyası birbirinden ayrılabilir. Hangi çizgilerin referanstan alındığı, hangilerinin yorumlandığı açıklanır; yeniden üretilen parça tarihî orijinal diye sunulmaz.'],
['gaziosmanpasa','bisiklet aksesuarı dekoratif kapak',
'Bisikletteki dekoratif aksesuar kapağı için bağlantı yeri ve hareketli parçalara uzaklık gösterilir. Fren, direksiyon, teker tutma veya yapısal bağlantı görevleri basit kapak üretiminden kesin biçimde ayrılır.',
'Kapağın yerinde tutulması kadar teker, kablo ve hareket alanıyla çarpışmaması önemlidir. Güvenliği etkileyen görevi belirsiz bir parçayı benzer görünüyor diye yeniden üretime almak yerine kapsam netleştirilir.',
'Baskı öncesi kapağın montaj kulağı ve erişilebilir kenarları dosyada işaretlenir. Dış ortam bilgisi değerlendirilir; darbe koruması veya sürüş güvenliği için belgesiz bir dayanım iddiası verilmez.',
'Numune bisiklet sabitken ve kullanım dışındayken yerleşim açısından incelenir. Bağlantı sıkışması veya hareketli bölüme yaklaşma varsa revizyon gerekir; bu kontrol sürüş testi yerine geçmez.',
'Tarama referansı kapağın karşılık yuvasını ve yakınındaki hareket alanını içermelidir. Sadece dış yüzey alındığında montajın niçin belirli yönde yapıldığı kaybolabilir; yön bilgisi fotoğrafa eklenir.',
'Sökülemeyen parçanın arka yüzü taranamıyorsa erişim sınırı bildirilir. Hareketli mekanizmayı çalıştırarak veri alma varsayılmaz; güvenli sabit konum ve gerekli kapsam önceden belirlenir.',
'CAD modelinde dekoratif yüzeyden önce montaj noktası ve yasak temas bölgeleri tanımlanır. Kapağın genişletilmesi hareket alanına giriyorsa estetik tercih teknik yerleşim kararını geçersiz kılamaz.',
'Dosya teslimi aksesuar kapamasıyla sınırlı işlevi belirtir. Fren veya direksiyon bileşeninin yerine kullanılacak genel bir parça etiketi verilmez; farklı montaj konumları ayrı varyant olarak kontrol edilir.'],
['gungoren','dikiş makinesi dış makara tutucu kapağı',
'Dikiş makinesinde dış makara düzenleyici kapak eksikse makara mili, kapak oturma yeri ve ipliğin geçişi belgelenir. İğne, hareket aktarımı veya koruyucu muhafaza işlevi bu örnekten ayrıca ayrılır.',
'Kapağın ipliği sürtmeden yönlendirmesi ve makaraya erişimi koruması değerlendirilir. İplik kopması veya mekanik zamanlama sorunu varsa yalnızca kapağı yenilemek arızayı gideren çözüm olarak sunulmaz.',
'Baskı planında ipliğe temas eden kenarın pürüzü ile mil deliğinin ölçüsü ayrı ele alınır. Destek izlerinin iplik yolunda kalmaması hedeflenir; son işlemin kapsamı dosya incelemesinde belirlenir.',
'Numune makine kapalıyken yerleştirilir ve iplik elle kontrollü geçirilir. Keskin temas, makara sıkışması ve kapak salınımı kaydedilir; mekanik uyum üretim hızında çalışma doğrulaması değildir.',
'Tarama öncesi iplik yolu ve kapağın takıldığı yön fotoğraflanır. Parçanın dış formundan anlaşılamayan alt tırnak veya pim varsa bunların görüş alanı ayrı kontrol edilir.',
'İnce iplik kanalı veri içinde dolmuş görünebilir. İpliğin gerçekten geçtiği açıklık tamamlayıcı ölçüyle doğrulanmadan tarama dosyası doğrudan baskıya yönlendirilmez; yüzey onarımı açıklığı kapatmamalıdır.',
'Modelleme makara ekseni ve iplik çıkış doğrultusunu ortak referansta kurar. Daha büyük makara için değişiklik isteniyorsa komşu gövdeye erişim ve kapak açılma alanı yeniden değerlendirilir.',
'CAD tesliminde iplik temas kenarları ile takılma yüzeyleri ayrılır. Kullanıcının mevcut makara ölçüsü dosya notuna girer; bütün makara tiplerine uyum varsayımıyla tek model açıklaması yazılmaz.'],
['kadikoy','fotoğraf makinesi dış vizör lastiği taşıyıcısı',
'Vizör çevresindeki plastik taşıyıcı kırıldıysa yumuşak göz temas parçasıyla raylı bağlantıyı ayırın. Kamera modeli yanında ray kesiti ve kilitleme çıkıntısı fotoğrafları değerlendirme için gerekir.',
'Taşıyıcının kabulü raydan kaymaması, ekran hareketini engellememesi ve kullanıcı temasını rahatsız etmemesidir. Kamera gövdesinin sızdırmazlığı veya darbe koruması bu dış parçanın geometrisiyle doğrulanmaz.',
'Baskıda ince ray dudakları ve yumuşak parçanın oturduğu kenar korunmalıdır. Görünür yüzey için yapılan son işlemin ray boşluğunu değiştirmemesi üretim incelemesinin ayrı bir başlığıdır.',
'İlk örnek kamerayı çalıştırmaya gerek olmadan ray üzerinde denenir. Zorlama, sürtme ve kilit temas noktası kaydedilir; gözle temas eden yumuşak bileşenin uygunluğu ayrıca değerlendirilir.',
'Tarama referansı sağlam taşıyıcının alt raylarını kapsamalıdır. Kamera üzerindeki kızak da belgelenir; dış oval biçimi kopyalamak küçük kilitleme ayrıntısını tanımlamaya yetmez.',
'Siyah parlak ray yüzeyi ve derin kanal farklı veri zorlukları yaratabilir. Kameraya hazırlık malzemesi uygulanacağı varsayılmaz; koruma şartları ve numunenin güvenli erişimi önce belirlenir.',
'CAD modelinde kamera rayıyla taşıyıcının kilit noktası önceliklidir. Göz çevresindeki yumuşak elemanın kendi geometrisi ayrı tanımlanır; sert baskı aynı temas malzemesinin eşdeğeri olarak sunulmaz.',
'Teslimde kamera varyantı ve takma yönü açıkça yazılır. Aynı marka içinde benzer görünen raylara toplu uyum iddiası verilmeden her bağlantı referansı ayrı kontrol edilir.'],
['kagithane','bilgisayar kasası dekoratif ön kapak klipsi',
'Bilgisayar ön panelindeki klips kırıldıysa paneli tutan bağlantı ile havalandırma veya koruyucu işlev birbirinden ayrılır. Klips yuvası, kablo konumu ve panel sökme yönü talebe eklenmelidir.',
'Panelin kasaya oturması, sökülürken kabloları çekmemesi ve hava açıklığını kapatmaması değerlendirilir. Isı ve elektrik güvenliği gereksinimleri bilinmeden bütün kasa parçalarına aynı baskı çözümü önerilmez.',
'Klips baskısında esneme kolu ile panel tabanına birleşen kök incelenir. Geriye dönük takma işlemi veya destek temizliği ince dili zayıflatabilir; numune yönü kullanım hareketiyle birlikte seçilir.',
'Deneme kasanın enerjisi kesilmişken boş panelde yapılır. Klipsin oturma sesi tek başına yeterli değildir; panel aralığı, sökme erişimi ve kablolara temas ayrıca görüntülenir.',
'Tarama için sağlam komşu klips kullanılabilir ancak her klips aynı yönü taşımayabilir. Kasa üzerindeki karşılık deliğiyle birlikte konumu işaretlemek, yanlış aynalanmış model oluşturulmasını önler.',
'Panelin arkasındaki kablolar veya metal sac klips yüzeyini örtebilir. Gizli bağlantı boşlukları dış taramayla ölçülmüş kabul edilmez; güvenli sökme ve ek ölçü gereksinimi kapsamda belirtilir.',
'CAD tasarımında klipsin panel üzerindeki konumu ile kasadaki yuva ilişkisi kurulur. Daha sıkı tutması için gövdeyi rastgele büyütmek yerine sökme hareketi ve montaj sırası birlikte incelenir.',
'Dosya teslimi sağ, sol veya orta klips ayrımını içerebilir. Varyant kodları panel krokisiyle eşleşir; havalandırma açıklığına giren değişiklikler dekoratif revizyon başlığı altında gizlenmez.'],
['kartal','otomobil iç trim kör tapası',
'Araç içindeki kör tapa için bulunduğu panelin fotoğrafı, açıklık biçimi ve varsa sağlam eş parça istenir. Hava yastığı kapağı, kemer bağlantısı veya güvenlik sistemine ait parçalar bu dekoratif örnekten ayrılır.',
'Değerlendirme tapanın açıklığı kapatması ve çevre paneli zorlamadan tutulması üzerine kurulur. Araç içi sıcaklık ve güneş maruziyeti paylaşılmalıdır; dış görünüş benzerliği otomotiv uygunluk belgesi değildir.',
'Baskıya hazırlıkta tırnak yönü, panel kalınlığı ve görünen yüzey tercihi belirlenir. İmalat malzemesi, araç içi koşullar değerlendirilmeden yalnızca renk eşleşmesi üzerinden seçilmez.',
'İlk numune park halindeki araçta ilgili yuva üzerinde kontrol edilir. Oturma, sökme erişimi ve çevre kaplamaya baskı değerlendirilir; sürüş güvenliği veya çarpışma davranışına ilişkin sonuç çıkarılmaz.',
'Tarama referansında tapanın ön yüzü kadar arka tırnaklar da bulunmalıdır. Sağlam parça başka donanım paketinden geldiyse panel açıklığının aynı olduğu ölçüyle teyit edilir.',
'Yumuşak trim yüzeyi baskıyla şekil değiştiriyorsa tarama konumu önemlidir. Delik çevresindeki deformasyon ölçülen durum olarak kaydedilir; yeni parçada korunması gereken özgün formdan ayrılır.',
'Modelleme kör tapanın oturma düzlemi ve tırnak mesafeleriyle başlar. Görünen kontur iç mekân yüzeyiyle ilişkilendirilir; güvenlik sistemi üstünü kapatan yeni bir kullanım bu işin kapsamına eklenmez.',
'CAD tesliminde araç ve panel varyantı tanımlanır. Çizim aynı model yılındaki her donanıma uyuyor diye etiketlenmez; onay belirli montaj yuvası ve incelenen numuneye bağlanır.'],
['kucukcekmece','buzdolabı dış raf etiketi tutucusu',
'Raf önündeki etiket tutucusu için raf kenarı kesiti, etiket ölçüsü ve sökme yönü kaydedilir. Gıda taşıyan rafın yapısal desteği ile dış etiket klipsi farklı talepler olarak değerlendirilir.',
'Etiketin okunması, çıkarılıp yenilenebilmesi ve kapak kapanmasını engellememesi kabul başlıklarıdır. Soğuk ortam, temizlik ve olası gıda teması belirtilir; uygunluk yalnızca plastik görünüşten çıkarılmaz.',
'Baskıda etiketi kavrayan ince dudak ve rafa geçen klips ayrı incelenir. Etiket yerleştirme ağzının son işlemle kapanmaması gerekir; gıda temasına uygunluk belgesiz şekilde ürün açıklamasına eklenmez.',
'Numune boş raf kenarında oturtulur ve gerçek etiketle denenir. Kâğıdın kıvrılması, tutucunun gevşemesi ve komşu kapakla temas kaydedilir; soğukta uzun dönem davranış bu ilk kontrolden varsayılmaz.',
'Tarama için rafın ön profili ve sağlam klipsin iç yüzeyi yeterli olabilir. Buzdolabının bütün iç hacmini ölçmek yerine hangi bağlantı kesitinin gerekli olduğu baştan belirlenir.',
'Şeffaf tutucu veya parlak raf kenarı optik ölçüde hazırlık gerektirebilir. Temas ve temizlik şartları korunarak yöntem değerlendirilir; malzemenin gıda güvenliği tarama verisinden okunamaz.',
'CAD modelinde etiket kalınlığı, görünür alan ve raf kavrama ölçüsü ayrı parametrelerdir. Daha büyük etiket isteniyorsa kapı kapanması ve yan raflarla çakışma kontrolüne yeni varyant eklenir.',
'Teslimde klipsin raf taşıyan parça olmadığı açıklanır. Model, etiket değiştirme hareketini ve temizleme erişimini göstermelidir; bu işlevlerin incelenmediği yalnızca görünüş dosyası tamamlanmış sayılmaz.'],
['maltepe','panjur ip kılavuz kapağı',
'Panjur ipinin geçtiği dış kılavuz kapak kırıldıysa ip yolu ve sabitleme noktaları birlikte belgelenir. Panjuru taşıyan, frenleyen veya kopmayı önleyen mekanizma basit yüzey kapağıyla karıştırılmaz.',
'Kapağın ipi keskin kenardan uzak tutması ve erişilebilir bağlantıyı örtmesi değerlendirilir. Panjur sıkışması veya taşıyıcı arızası varsa yeni kapak bunları gideren çözüm olarak sunulmaz.',
'Baskıda ipin sürtündüğü geçiş kenarıyla duvara oturan taban ayrı işlev taşır. Kanal açıklığı ve temizleme sonrasındaki yüzey durumu üretim incelemesine girer; güvenlik yükü bilinmeden kapasite belirtilmez.',
'İlk numune mekanizma güvenle kullanım dışındayken yerleştirilir. İpin açıklıkta rahat hareketi ve kapağın sabitlenmesi gözlenir; bu deneme panjurun taşıma veya frenleme işlevinin testi sayılmaz.',
'Tarama referansı eski kapağın duvara bakan yüzünü ve ip çıkış yönünü içerir. Sıva veya boya birikimi tasarım geometrisinden ayrılır; kapakta sonradan açılan delikler ayrıca işaretlenir.',
'Duvar içinde kalan mekanizma yüzeyleri dış taramayla elde edilemez. Çalışma yalnızca kılavuz kapağın erişilebilir formunu kapsıyorsa bu sınır teslim dosyasına da taşınır.',
'Modelleme vida aralığı, ip doğrultusu ve duvar çıkıntısının ilişkisini kurar. İp sürtmesini azaltmak için önerilen kenar değişikliği, mekanizmanın asıl yolunu değiştirmeden değerlendirilir.',
'CAD kontrolünde ipin farklı hareket konumlarındaki açıklığı gösterilir. Model adı kılavuz kapağı olarak korunur; mekanik fren veya yük tutucu yerine kullanılacağına dair kapsam genişletilmez.'],
['pendik','bebek arabası aksesuar gözü kapağı',
'Bebek arabasındaki küçük aksesuar gözü kapağı için işlev ve bulunduğu konum açıkça belirtilmelidir. Fren, katlanma kilidi, emniyet kemeri veya taşıyıcı bağlantı bu dış kapama talebinin dışında değerlendirilir.',
'Ön inceleme kapağın çocuk erişiminde olup olmadığını ve ayrılınca küçük parça oluşturup oluşturmadığını kapsar. Mekanik olarak yerine oturması çocuk ürünü uygunluğu anlamına gelmez; üretici çözümü gerekebilir.',
'Üretimi uygun bulunan erişim dışı dekoratif kapakta bağlantı ve keskin kenarlar dosyada gösterilir. Çocuk temasına veya ağıza almaya uygunluk belgesi olmadan genel güvenli malzeme iddiası kurulmaz.',
'Numune ürün kullanım dışında ve yüksüz durumdayken kontrol edilir. Kapak açılma yönü, ayrılabilir parçalar ve komşu mekanizmaya temas kaydedilir; çocuk kullanımına teslim bağımsız uygunluk değerlendirmesine bağlıdır.',
'Tarama için kapağın açık ve kapalı fotoğrafları ile bağlantı yüzeyleri hazırlanır. Arabayı katlayınca konum değişiyorsa hangi sabit duruşta veri alınacağı güvenli biçimde kararlaştırılır.',
'Yumuşak kumaşın örttüğü arka bağlantılar tarama dışında kalabilir. Gizli yüzeyler elde edilmiş gibi gösterilmez; sökme veya ek ölçü ihtiyacı ürünün güvenlik mekanizmasını etkilemeden değerlendirilir.',
'CAD kapsamı aksesuar gözü dış kapağı olarak tanımlandığında taşıyıcı bağlantılara müdahale edilmez. Açılma hacmi, ayrılabilir elemanlar ve çocuğun erişebildiği kenarlar görünür işaretlerle ele alınır.',
'Teslim kontrolü tasarımın işlev sınırını açıklar. Fren, kemer ya da katlanma kilidine uyarlanabilen genel bir parça önerisi yapılmaz; çocuk ürünü uygunluğuna dair belgesiz onay yazılmaz.'],
['sancaktepe','depolama kutusu etiket çerçevesi',
'Depolama kutusuna eklenecek etiket çerçevesinde kutu yüzeyinin düzlüğü, etiket boyutu ve takma yöntemi belirtilir. Kutu kapağını kilitleyen bağlantı ile yalnızca bilgi taşıyan çerçeve ayrı parçalardır.',
'Çerçevenin okunaklı etiketi tutması, eldivenli erişimi ve kutular üst üste geldiğinde ezilmemesi değerlendirilir. Yapıştırma isteniyorsa yüzey malzemesi bilinmeden her kutuya aynı bağlantı önerilmez.',
'Baskıda etiket kanalının genişliği ve yüzeye bakan montaj kulakları kontrol edilir. İnce köşelerin temizlenebilmesi planlanır; çerçeveye eklenen kabartma yazı etiket değiştirme yolunu kapatmamalıdır.',
'İlk örneğe gerçek kalınlıkta etiket takılır ve kutuların yerleşimi incelenir. Kâğıdı buruşturan kanal veya komşu kutuya çarpan çıkıntı revizyon için ölçü ve fotoğrafla kayıt edilir.',
'Tarama için kutunun bütün hacmi yerine çerçevenin oturacağı yüzey yeterli olabilir. Yüzeydeki nervür ve tutamak mesafeleri belirtilir; etiketin görünür kalacağı alan referansa dahil edilir.',
'Esnek kutu boşken ve doluyken farklı bombe yapabilir. Tarama durumunu kaydetmek gerekir; ölçülen eğrilik sabit kabul edilerek her dolulukta tam temas vaat edilmez.',
'Modelde etiket yuvası ile kutuya bağlanan yüzey ayrı düzenlenebilir bölümler olarak ele alınır. Farklı etiket boyutları isteniyorsa okunur alan ve tutma payı her varyantta yeniden kontrol edilir.',
'Dijital teslimde çerçeve yönü ve etiket sürme ağzı gösterilir. Önden görünen render, gerçek kutu düzenindeki okunurluk ve erişim incelemesinin yerine geçmez; bağlantı donanımı kapsamı ayrıca yazılır.'],
['sariyer','katlanır sehpa dış menteşe koruyucusu',
'Katlanır sehpanın dış menteşe koruyucusunda kırık varsa taşıyıcı menteşe, kilit ve yalnızca kapatan plastik birbirinden ayrılır. Koruyucu bir parça parmak sıkışmasını önlüyorsa bu işlev ayrıca değerlendirilmelidir.',
'Talep sehpanın açık ve katlı konumlarını gösteren fotoğraflarla başlar. Yeni dış kapak taşıyıcı arızayı gizleyemez; hareket açıklığı ve kullanıcı erişimi için hangi kontrollerin gerektiği yazılır.',
'Uygun görülen kapama parçasında menteşe çevresindeki açıklıklar ve sabitleme tırnakları baskı dosyasına işlenir. Koruma işlevi doğrulanmadan parmak sıkışmasını önler şeklinde bir ürün iddiası eklenmez.',
'Numune sehpa yüksüz ve kontrollü hareket ettirilirken incelenir. Katlanmada kapağın sıkışması, ayrılması veya hareketi sınırlaması kayıt edilir; taşıma kapasitesi bu kontrolden hesaplanmış sayılmaz.',
'Tarama verisi tek konumdaki yüzeyi anlatır; açık ve kapalı konum ilişkisini fotoğrafla destekleyin. Hareketli ekleme temas ederek ölçü almanın güvenli yöntemi çalışma öncesinde belirlenir.',
'Menteşe arkasındaki temas yüzeyi görüş hattı dışında kalabilir. Sökme mümkün değilse bu eksik açıkça işaretlenir; kapalı boşluk taranmış gibi modelde kesin ölçüyle gösterilmez.',
'CAD modelinde menteşenin hareket hacmi ile kapağın sabit durduğu yüzey ayrılır. Dış biçimi büyütmek erişilebilir boşluğu daraltıyorsa tasarım yenilenir; sadece güzel görünüş onay gerekçesi olmaz.',
'Teslim incelemesi açık, ara ve katlı konum çizimlerini karşılaştırır. Kapağın taşıyıcı veya emniyet kilidi olmadığı işlev notunda belirtilir; koruma gereksinimi varsa ayrıca doğrulanacak koşul olarak kalır.'],
['silivri','stor perde dış montaj rozeti',
'Stor perde bağlantısını örten dekoratif rozet eksikse ana taşıyıcı brakete dokunmadan kapama ölçüsü alınır. Perdeyi tutan parça ile vida çevresini örten ince kapak farklı işlevlere sahiptir.',
'Rozetin yerine oturması ve kumanda hareketini engellememesi ilk kabul başlıklarıdır. Braket gevşekse bunu daha sıkı dekoratif kapakla düzeltmeye çalışmak yerine taşıyıcı bağlantının sorunu ayrıca ele alınır.',
'Baskı için rozetin duvara oturma yüzeyi, tırnakları ve vida başına kalan açıklık gösterilir. Mevcut duvar eğriliği varsa düz parçanın nasıl oturacağı numune kontrolünde değerlendirilir.',
'İlk örnek perde kullanım dışındayken brakete zorlamadan takılır. Kapağın çıkıntı yapması, zincire sürtmesi veya bakım vidasını kapatması fotoğraflanır; taşıma güvenliği hakkında sonuç çıkarılmaz.',
'Tarama referansı dekoratif kapağın iç tırnaklarıyla taşıyıcı dış formu kapsar. Duvardaki boya kabarması ve sonradan sürülmüş dolgu özgün kapak geometrisinden ayrı işaretlenir.',
'Braketin tavana veya duvara yakın arka yüzü görülemiyorsa kapsam sınırlanır. Parçayı sökmeden tüm iç tutunma ayrıntısı elde edildiği varsayılmaz; ek ölçü ihtiyacı açıklanır.',
'Modelleme dekoratif rozetin görünür sınırı ve braketle tutunma ilişkisini kurar. Bakım için erişilen vida başını kapatmamak veya gerektiğinde rozeti sökebilmek tasarım girdisidir.',
'Teslim dosyasında sağ ve sol montaj şekilleri ayrı gösterilir. Rozetin perdeyi taşıyan bağlantı olmadığı belirtilir; yeni görünüş varyantı mevcut braketin yapısal eşdeğeri olarak sunulmaz.'],
['sultanbeyli','kapı stoperi dış taban kılıfı',
'Kapı stoperinin dış plastik kılıfı eksikse tabanın sabitlenmesi ve kapıya değen yumuşak bölüm ayrı tanımlanır. Yangın kapısı, kaçış kapısı veya güvenlik işlevi olan düzenekler bu basit örneğe dahil edilmez.',
'Kılıfın montaj vidasına erişimi ve çevrede takılma yaratmaması değerlendirilir. Kapı darbelerini durduracak taşıyıcı görevi varsa yalnızca mevcut görünüşü kopyalamak yeterli kabul ölçütü oluşturmaz.',
'Üretim planında zemine oturan kenar, vida boşluğu ve yumuşak tamponun yuvası ayrı gösterilir. Sert baskı parçanın elastik tampon yerine geçeceği varsayılmaz; hangi bölümün üretileceği açık tutulur.',
'İlk baskı kapı hareket ettirilmeden yerleşim kontrolüne alınır. Tabanın kalkması, vida erişimi ve tamponla birleşmesi kaydedilir; darbe dayanımı veya kapı güvenliği testi yapılmış gibi raporlanmaz.',
'Tarama için taban kılıfını sabit parçadan ayıran birleşme hattını fotoğraflayın. Çatlak ve eğilme varsa bunlar onarılacak kusur olarak işaretlenir; özgün form diye aynen korunmaz.',
'Zemine bitişik alt yüzey tarama hattı dışında kalabilir. Erişilebilir dış kayıt ile gerçek montaj ölçüleri birlikte değerlendirilir; kapalı tabanın iç bağlantısı tahminle tamamlanmaz.',
'CAD çalışması taban vida merkezi, zemin düzlemi ve tampon eksenini ortak referansta toplar. Görünen kılıf büyütülürse ayak temas alanı ve temizlik erişimi yeniden kontrol edilir.',
'Dijital teslimde kılıf ile darbe emen parça ayrı kodlanır. Tasarımın yalnızca kapama işlevi varsa model adına taşıyıcı stoper kapasitesi eklenmez; güvenlik kapısı kullanımı ayrıca değerlendirilmeden önerilmez.'],
['sultangazi','raf dikmesi dekoratif uç kapağı',
'Raf dikmesinin açık ucuna kapak isteniyorsa profil kesiti, iç boşluk ve keskin kenarlar gösterilir. Rafı taşıyan bağlantı, devrilme önleyici eleman veya yük dağıtan ayak bu kapama örneğiyle bir tutulmaz.',
'Yeni kapağın profilde tutulması ve erişilebilir keskin ucu örtmesi beklenir. Rafın eğilmesi ya da sallanması varsa bunu kapağı kalınlaştırarak giderdiğimizi söylemeden asıl bağlantı sorunu ayrılır.',
'Uç kapak baskısında içe geçen kanatlarla dış flanşın işlevi farklıdır. Profil çapakları ve boyası montaj ölçüsünü etkileyebilir; gerçek örnek görülmeden nominal kesit üzerinden kesin uyum vaat edilmez.',
'Numune yüksüz profil ucunda oturtulur. Flanşın keskin kenarı tamamen kapatması ve kapağın sökme erişimi değerlendirilir; rafın yük taşıma kapasitesi bu yerleşim kontrolünden türetilmez.',
'Tarama için profilin açık kesiti ve varsa sağlam eş kapak kullanılabilir. Dıştaki dekoratif kontur kadar iç kanatların profille temas eden bölgeleri de kayıt kapsamına alınır.',
'Kapalı kutu profilin derin iç yüzeyi görülemeyebilir. İhtiyaç yalnızca ağızla sınırlıysa ölçü kapsamı buna göre tanımlanır; uzun profil boşluğu taranmış gibi dijital dosyaya eklenmez.',
'CAD modelinde profil iç kesiti ve dış kapama sınırı ayrılır. Köşelerdeki boya veya kaynak birikimi ölçüde varsa yeni kapağın nereye oturacağı çizimde açıkça kontrol edilir.',
'Teslim edilen kapak modeli hangi profil örneğine göre hazırlandığını taşır. Aynı nominal ölçülü bütün raflara evrensel uyum iddiası yerine gerçek kesit ve montaj yönü belirtilir.'],
['sile','pencere sineklik köşe kapaması',
'Sineklik köşesindeki dış kapama için çerçeve kesiti ve birleşme yönü kaydedilir. Çerçeveyi taşıyan yapısal köşe bağlantısı ile yalnızca açık ucu örten kapak aynı parça değildir.',
'Kapamanın tülü sıkıştırmaması, pencere hareketini engellememesi ve dışarıda gevşek kalmaması değerlendirilir. Yüksek konumda düşebilecek parçalarda montaj güvenliği ayrıca ele alınmalı, görünüş uyumu yeterli sayılmamalıdır.',
'Baskı hazırlığında çerçeveye giren dudak ve tül tarafındaki açıklık gösterilir. Güneş ve yağış maruziyeti belirtilir; belirli dış ortam ömrü veya rüzgâr dayanımı ölçülmeden vaat edilmez.',
'İlk örnek güvenli erişimli ve kullanım dışı çerçevede incelenir. Tülün sıkışması, pencereye sürtme ve kapağın gevşemesi kaydedilir; montajın düşme riski uygun biçimde değerlendirilmeden kullanıma geçilmez.',
'Tarama için köşenin iki profil yönü ve tül kanalı birlikte görüntülenir. Kırık kapakta eksik yüzey varsa sağlam karşı köşenin gerçekten aynı bağlantıyı taşıyıp taşımadığı kontrol edilir.',
'Tül gibi ince ve esnek ağ, katı kapakla aynı tarama yüzeyi değildir. Ölçü kapsamı profil ve kapama üzerinde tanımlanır; gerilme durumundan çıkan geçici form kalıcı geometri sayılmaz.',
'Modelleme iki profilin köşe açısı ve kapamanın oturma sırasıyla başlar. Tülü tutan kanala taşan değişikliklerden kaçınmak için kesit görünüşü teslim öncesi değerlendirmeye dahil edilir.',
'CAD dosyasında dekoratif kapama ile taşıyıcı köşe parçası açıkça ayrılır. Varyantın sağ veya sol köşede kullanımı belirtilir; montaj emniyeti için gereken değerlendirme çizim onayıyla ikame edilmez.'],
['sisli','ofis koltuğu ayar kolu dış tutamağı',
'Ofis koltuğunda dış ayar tutamağı kırıldıysa metal kol, kilit mekanizması ve plastik kavrama parçası ayrı gösterilir. Koltuğu taşıyan gaz pistonu veya yapısal bağlantı basit tutamak kapsamına alınmaz.',
'Talep, tutamağın erişilebilirliği ve doğru ayar hareketini aktarması üzerine kurulur. Mekanizma kendi kendine bırakıyorsa plastik sap üretimi arızayı gidermiş sayılmaz; çalışma işlevi öncelikle açıklanır.',
'Baskıda metal kola geçen iç yuva ve elin kavradığı dış gövde incelenir. Dış form büyütülecekse yan döşemeye sürtme ve kolun hareket mesafesi üretim öncesinde değerlendirilir.',
'İlk örnek koltuk yüksüzken uygun koşulda takılır. Sapın milde dönmesi, köşede çatlama veya erişim zorluğu kaydedilir; oturma yükü ve piston güvenliği hakkında bu denemeden sonuç çıkarılmaz.',
'Tarama referansı sağlam tutamağın iç bağlantısını ve ayar kolunun kesitini kapsar. Kolu çekili tutarak alınan görüntü ile serbest durum arasındaki fark işaretlenmelidir.',
'Döşeme altındaki bağlantı görülemiyorsa erişim sınırlaması yazılır. Tarama dış sap biçimini verebilir; gizli sabitleme pimi veya vida ölçüsü ayrıca bilinmeden model tamamlanmış sayılmaz.',
'CAD modellemede ayar kolu ekseni, montaj deliği ve parmak erişim hacmi ortak referansa alınır. Sağ-sol kullanım farkı varsa dış kavrama formu aynı dosyanın aynası diye otomatik kabul edilmez.',
'Teslim kontrolü tutamağın hareket sırasındaki boşluğunu ve bağlantı yönünü kapsar. Model adı dış ayar sapı olarak sınırlandırılır; koltuğun yük taşıyan mekanizmasına eşdeğerlik iddiası eklenmez.'],
['tuzla','taşıma kasası etiket klipsi',
'Taşıma kasasındaki bilgi kartı klipsi için kasa cidarı, etiket kalınlığı ve üst üste koyma düzeni gösterilir. Kasayı kaldıran tutamak veya kilitleyen emniyet elemanı bu bilgi taşıyıcı parçadan ayrılır.',
'Klipsin etiketi tutması kadar kasalar taşınırken dışarıda takılacak çıkıntı oluşturmaması önemlidir. Temizlik ve dış ortam koşulları belirtilir; klipsin kasa yük kapasitesini artırdığı iddia edilmez.',
'Baskı dosyasında kasa kenarına geçen tutunma ayağı ve kartın girdiği açıklık işaretlenir. İnce kart kanalı destek sonrası kapanmamalıdır; renk kodları isteniyorsa teknik varyantlardan ayrı listelenir.',
'Numune boş kasada kart takıp çıkarılarak denenir. Kasalar bir araya geldiğinde çıkıntıya temas olup olmadığı kontrol edilir; bu kontrol yüklü istiflemenin güvenlik doğrulaması sayılmaz.',
'Tarama referansı kasanın ilgili nervürü ve klipsin temas ettiği dudaktır. Büyük kasanın tüm yüzeyi gerekli olmayabilir; etiket konumunun tutamak ve istif çizgisine göre yeri fotoğrafta gösterilir.',
'Kasa cidarı esnekse sıkıştırılarak ölçülmesi yanlış referans yaratır. Boş ve doğal duruş kaydedilir; montajdaki geçici şekil değişimi ideal katı geometri gibi sunulmaz.',
'Modelleme etiket yuvasını kasanın tutunma kesitiyle ilişkilendirir. Farklı depolama yönleri için yatay ve dikey seçenek düşünülüyorsa kartın yerçekimiyle çıkma ihtimali ayrıca incelenir.',
'CAD tesliminde klipsin kasa yönü ve kart değiştirme ağzı açık gösterilir. Etiket ölçüleri varyant kodlarına bağlanır; taşıma tutamağı veya istif kilidi olarak yeniden kullanım önerilmez.'],
['umraniye','kahve makinesi dış damlalık ızgara çerçevesi',
'Kahve makinesindeki damlalık dış çerçevesi için sıvı, sıcaklık ve temizlik koşulları açıklanmalıdır. İçecekle temas eden, basınç tutan veya elektriksel koruma sağlayan parçalar bu dış yerleşim örneğinden ayrılır.',
'Çerçevenin yerine oturması, ızgaranın çıkarılması ve haznenin boşaltılması birlikte değerlendirilir. Sıcak sıvı veya gıda teması uygunluğu belgelenmeden malzemeye genel kullanıma hazır onayı verilmez.',
'Baskı planında ızgarayı taşıyan dudak ve hazneye oturan kontur ayrı incelenir. Temizleme erişimi ve yüzey beklentisi dosyada belirtilir; su tutmama veya hijyen özelliği ölçülmeden varsayılmaz.',
'Numune makine kullanım dışındayken kuru yerleşim kontrolüne alınır. Haznenin çıkarılabilmesi ve ızgaranın düz oturması kaydedilir; sıcak sıvıyla kullanım bu mekanik kontrolden bağımsız değerlendirilir.',
'Tarama için çıkarılabilir haznenin çerçeveye temas eden ağzı ve eski çerçevenin alt yüzeyi referans olur. Kir, kireç ve aşınma özgün tasarım formundan ayrı belirtilmelidir.',
'Islak veya parlak yüzeyler ve dar oluklar veri alımını etkileyebilir. Numunenin temizleme ve korunma koşulları konuşulur; tarama verisi malzemenin hijyen veya sıcaklık uygunluğunu kanıtlamaz.',
'CAD modelinde hazne ağzı, ızgara oturma yüksekliği ve çıkarma yönü birlikte kurulur. Görünüş için yapılan kalınlık değişikliği sıvının akışını veya temizleme erişimini kapatıyorsa yeniden ele alınır.',
'Teslim edilen modelin kullanım kapsamı ve temas yüzeyleri açıklanır. Yalnızca yerleşim numunesi hazırlanmışsa sıcak sıvı veya gıda teması için nihai ürün diye adlandırılmaz; doğrulama ihtiyacı görünür kalır.'],
['uskudar','müzik standı dış ayar somunu tutamağı',
'Müzik standında dış sıkma tutamağı kırıldıysa metal dişli eleman ve plastik kavrama gövdesi ayrı gösterilir. Standı taşıyan kilit işlevi varsa yeni parça için yalnızca dış biçim uyumu yeterli değildir.',
'Değerlendirme dişli elemanın nasıl sabitlendiği ve kullanıcı tarafından nasıl sıkıldığıyla başlar. Standın kayması, metal diş aşınması veya gövde eğriliği plastik tutamakla giderilmiş sayılmaz.',
'Baskı hazırlığında metal ek parçanın yuvası ve dönmeyi engelleyen yüzeyler incelenir. Sıkma kuvveti bilinmeden dayanım değeri verilmez; elde tutuş biçimiyle bağlantı geometrisi birlikte değerlendirilir.',
'İlk örnek stand yüksüzken montaj ve kavrama açısından denenir. İç metal parçanın dönmesi veya yuvadan ayrılması revizyon nedenidir; bu kontrol standın yük taşıma yeterliliğini doğrulamaz.',
'Tarama için tutamak içindeki metal bağlantı geometrisi ve sağlam dış yüzeyler belgelenir. Kırık parçada yerinden oynamış somun varsa bulunduğu konum orijinal montaj yeri olarak alınmaz.',
'Derin diş veya metal-plastik birleşimi optik taramada tam yakalanamayabilir. Standardı bilinen bağlantı ölçüsü ayrıca doğrulanır; tarama çıktısı diş eşleşmesinin doğrudan kanıtı sayılmaz.',
'CAD çalışmasında metal somun yuvasının dönmeye karşı tutunması ve el erişimi önce çözülür. Büyük tutamak tercihinin çevredeki borulara çarpıp çarpmadığı gerçek stand konumunda değerlendirilir.',
'Dijital teslimde plastik kavrama gövdesiyle metal donanım ayrı kalemlerdir. Model üzerinde yazan diş bilgisi gerçek parçayla karşılaştırılır; belirsiz sıkma koşullarına evrensel taşıma garantisi eklenmez.'],
['zeytinburnu','duvar saati askı deliği dış kapağı',
'Duvar saatindeki dış kapak eksikse saati taşıyan askı bağlantısıyla dekoratif kapamayı ayırın. Ağırlığı tutan plastik kırılmışsa bunun basit arka kapak değişimi olmadığı baştan belirtilmelidir.',
'Ön değerlendirme kapağın pil erişimini ve duvara oturma mesafesini korumasına bakar. Askı hasarı veya gövde çatlağı varsa yeni kapak bu sorunları gizleyen bir onarım olarak kabul edilmez.',
'Baskı dosyasında kapak tırnakları, pil açma bölgesi ve duvara bakan çıkıntılar gösterilir. Saatin ağırlığını taşıması beklenen alanlar varsa malzeme ve doğrulama kapsamı ayrı ele alınır.',
'Numune saat masada ve kullanım dışında dururken denenir. Kapağın kapanması, pil erişimi ve mekanizmaya temas kontrol edilir; duvara asılı taşıma güvenliği bu ilk uyum gözleminden çıkarılmaz.',
'Tarama için arka kapağın dış yüzeyi kadar mekanizma tarafındaki boşluklar da gösterilir. Eğilmiş veya çatlamış alanlar işaretlenir; saatin duvara mesafesi için sağlam oturma noktaları referans alınır.',
'Saat mekanizmasının altında kalan kapak yüzeyleri görünmeyebilir. Hangi parçaların güvenle ayrılabildiği önceden konuşulur; kapalı alanların ölçüsü yalnızca dış kabuk verisinden kesinleştirilmez.',
'Modellemede kapak oturma çevresi, pil erişimi ve mekanizma boşluğu birlikte kurulur. Askı deliği yük taşıyorsa bu tasarım görevi ayrıca tanımlanır; dekoratif modelin içinde fark edilmeden bırakılmaz.',
'Teslim kontrolü kapağın işlev sınırını ve referans saat varyantını belirtir. Duvar montajına ilişkin bilinmeyen kapasite değeri dosyaya eklenmez; yüksüz uyum denemesiyle nihai kullanım değerlendirmesi ayrılır.'],
['ornek','randevulu numune kabulü ve parça karşılaştırması',
'Atölye görüşmesi için tek bir arızayı açıklayan numune takımı hazırlayın: kırık plastik, sağlam eş varsa o parça ve cihazda kalan bağlantının fotoğrafı. Küçük kırıkları birbirine yapıştırmadan önce mevcut durumlarını kaydedin.',
'Görüşmenin çıktısı ihtiyaç duyulan ölçüler, yeniden yapılacak bölüm ve kontrol edilecek montaj koşullarıdır. Numuneyi teslim etmek otomatik üretim onayı değildir; kapsam, iade isteği ve örneğin korunma şartı birlikte yazılır.',
'Randevuya üretim dosyasıyla geliyorsanız dosyanın sürümünü, ölçü birimini ve gerçek montaj yuvasını gösteren görüntüyü hazırlayın. Dosyadaki bağlantının hangi parçaya oturacağı bilinmeden baskı adedi kesinleştirilmez.',
'İlk baskı tesliminde görsel kontrol ile cihaz üzerindeki uyum kontrolü ayrılır. Atölyede cihaz yoksa numunenin nerede deneneceği belirlenir; denenmemiş bağlantı için yerine tam oturdu ifadesi kullanılmaz.',
'Numune tarama görüşmesinde hangi yüzeylerin korunacağı ve hangi kırıkların yeniden yorumlanacağı işaretlenir. Eski parçanın iadesi, üzerine işlem yapılma sınırı ve tarama sonunda istenen dosya türü ayrıca kayda girer.',
'Cihaz atölyeye getirilemiyorsa yerinde tarama değerlendirmesi için montaj fotoğrafı ve erişim bilgisi gerekir. Kapalı veya sökülemeyen yüzeylerin mutlaka ölçülebileceği kabul edilmez; ölçüm kapsamı çalışma öncesi belirlenir.',
'Modelleme görüşmesine ölçülü kroki, varsa önceki dosya ve değişiklik isteği getirin. Birden fazla kişi ölçü aldıysa hangi referansın esas olduğu yazılır; çelişen değerler sessizce ortalanarak tasarıma geçirilmez.',
'Çizim incelemesinin sonunda parça kodu, revizyon ve kabul edilecek ölçüler birlikte okunur. Görüşmede verilen görsel onay, cihazda yapılmamış montaj deneyinin yerine geçmez; bir sonraki kontrol adımı açık kalır.'],
];
