// The location fact below is retained from the existing owner statement recorded on 2026-10-02.
// New business claims or delivery commitments are not inferred from a city name.
export default {
'3dyanimda': ['İstanbul’da ürün prototipi ve 3D üretim talebi','İstanbul’daki ürün geliştirme projeniz için dijital dosya, numune amacı ve ilk deneme kapsamını tek talepte toplayın.','Dosyayla başlayacağınız adımı seçin','Yeni bir ürün fikrinde form denemesi için eskiz ve dış ölçüler, montaj kontrolü için bileşen bilgileri gerekir. İstanbul içindeki toplantı veya sunum tarihinizi numunenin kullanılacağı gün olarak belirtin. Dosyanın hazırlanması, fiziksel üretim ve taşıma sürelerini aynı işlem gibi değerlendirmeyin.','Numuneyi teslimden önce tanımlayın','Gönderilecek fiziksel örnek varsa hangi model revizyonunu temsil ettiğini yazın. Kırılgan yüzey ve aksesuarları fotoğrafla belgeleyin. Numune değerlendirmesiyle tekrar üretim kararının farklı tarihlerde olabileceğini planlayın; tüm ürün ekibinin aynı dosya sürümünü değerlendirmesini sağlayın.','İstanbul’un başka bir ilçesinden dosyayla başlayabilir miyim?','Evet; dijital talepte kullanım amacı, yaklaşık ölçü ve numune beklentisi paylaşılabilir. Fiziksel referans gerekip gerekmediği dosya değerlendirmesinin ardından netleştirilir.',['Prototipin kullanılacağı görüşme tarihi','Bileşen veya gövde referansları','Dijital veri ile fiziksel numunenin eşleştirilmesi'],
'İstanbul’daki ürün ekiplerinin dijital ön değerlendirmeye başlaması için atölyeye yolculuk yapması gerekmez. Mevcut işletme beyanında çalışma noktası Ataşehir, Örnek Mahallesi olarak kayıtlıdır. Gönderilecek örneğin hangi karar için inceleneceğini ve ürün ekibinin güncel revizyonunu paylaşın; şehir içindeki toplantınızın tarihi numunenin üretim ve taşıma planından ayrı değerlendirilir.',
'Fiziksel prototip gönderiminde kutu içindeki parçaları revizyon ve adet listesiyle eşleştirin. Hassas dış yüzeyleri ayrı koruyun. Teslim alacak kişinin bilgisi ile gerekli gün talep görüşmesinde belirlenir; İstanbul içi ulaşım için süre ayrıca teyit edilir.'],
'3dsanayi': ['İstanbul üretim ekipleri için aparat ve fikstür talebi','İş istasyonu görüntüleri, iş parçası referansı ve numune kabul planıyla İstanbul’daki üretim ihtiyacınızı teknik talebe dönüştürün.','Saha bilgisini dosya paketine alın','Atölye veya fabrikanın bulunduğu ilçe tek başına aparat kapsamını açıklamaz. Makine üzerindeki erişim, çalışma alanı ve iş parçasının yükleme biçimini gösterin. Saha ziyareti gerektiği düşünülüyorsa bunu ayrı ihtiyaç olarak belirtin; başlangıçta dijital veriyle hangi kararların verilebileceği değerlendirilebilir.','Üretim denemesini vardiya planına bağlayın','Aparat numunesini istasyonda deneyecek kişi ve uygun deneme aralığı belli olmalıdır. Numunenin atölyeden çıkışıyla üretim kabulünün aynı gün gerçekleşeceği varsayılmaz. Uygun parça varyantları, ölçüm cihazı ve kontrol sorumluları hazır olduğunda denemenin sonucu daha açık kaydedilebilir.','Saha kurulumu üretim fiyatına dâhil midir?','Kurulum, ziyaret veya yerinde ölçüm ihtiyacı teknik teklifte ayrıca belirtilir. Yalnızca bir parça üretim talebinin bunları otomatik kapsadığı düşünülmemelidir.',['İstasyon fotoğrafları ve iş parçası kodu','Numune denemesine uygun vardiya aralığı','Kalite ve üretim kabul sorumluları'],
'İstanbul genelindeki üretim taleplerinde öncelikle istasyon verisi ile iş parçası referansını birlikte inceleriz. Çalışma yeri için eldeki işletme beyanı Ataşehir, Örnek Mahallesi’ni belirtir; ilçe listesi ayrı tesisler bulunduğunu ifade etmez. Fabrikadan fiziksel numune gönderilecekse bunun üretimi aksatıp aksatmayacağı ve aynı örneğin kabul denemesinde gerekli olup olmadığı talep aşamasında konuşulur.',
'İş parçasını gönderirken aparat talep kodunu ve numuneye zarar verilmemesi gereken yüzeyleri ambalaj notuna ekleyin. Gelen referansın geri dönüş ihtiyacı ayrıca kaydedilir. Sevkiyat, kurulum ve üretim denemesi farklı adımlar olarak planlanır; ilçe seçimi teslim süresi taahhüdü oluşturmaz.'],
'maketyanimda': ['İstanbul’daki mimari sunumlar için maket proje planı','Maketin ölçeğini, sunum mekânını ve taşıma sınırlarını mimari dosyalarla birlikte değerlendirin.','Sunum mekânının ölçülerini paylaşın','Bir ofis masası, satış alanı veya etkinlik mekânı farklı taban ve izleme koşulları yaratır. Maketin geçeceği kapı, asansör veya merdiven ölçüsü büyük modellerde tasarımı etkileyebilir. İstanbul içindeki sunum noktası, yalnızca teslim adresi olarak değil kurulum gereksinimiyle birlikte ele alınmalıdır.','Kurulumla sunumu ayrı tarihlendirin','Maket parçalıysa mekânda birleştirme ve son kontrol için uygun zaman ayrılmalıdır. Hangi parçaların yerinde takılacağı, kaidenin kim tarafından hazırlanacağı ve taşıma kutusunun nerede tutulacağı belirtilir. Mimari model revizyonu devam ediyorsa son dosya tarihinin sunum takvimiyle ilişkisi ayrıca değerlendirilir.','Maket İstanbul içinde tek parça taşınır mı?','Toplam boyut, narin elemanlar ve giriş koşullarına göre karar verilir. Modüler tasarım veya ayrı taşıma kasası gerekiyorsa bunlar teklif kapsamına eklenir.',['Sunum yerinin giriş ve kaide ölçüleri','Son mimari dosya ve sunum günü','Kurulum gerektiren maket modülleri'],
'İstanbul’daki mimarlık ve gayrimenkul sunumlarında maketin kullanılacağı mekân, ölçek seçiminin bir parçasıdır. Proje çalışma noktası mevcut beyana göre Ataşehir, Örnek Mahallesi’ndedir. Avrupa ve Anadolu yakasındaki teslimler için modelin tek parça mı modüler mi taşınacağı, giriş koşulları ve kurulum zamanı talep görüşmesinde değerlendirilir; sunum günüyle taşıma gününü aynı kabul etmeyin.',
'Toplam taban ölçüsü, ambalaj hacmi ve çıkarılabilir parçalar taşıma planına yazılır. Teslim yerindeki kapı ve asansör bilgisi büyük maketlerde gereklidir. Kaideye yerleştirme, yerinde kurulum ve taşıma kutusu ayrı kapsam olabilir; kesin gün ve yöntem teklif değerlendirmesinden sonra belirlenir.'],
'parcayanimda': ['İstanbul’da kırık veya eksik plastik parça değerlendirmesi','Parçanızın fotoğrafını, montaj yuvasını ve kullanım görevini paylaşarak özel üretim için gerekli referansları belirleyin.','Parçayı göndermeden fotoğraflayın','Kırık örneğin konumu, sağlam yüzeyleri ve ayrılan küçük parçaları fotoğrafta gösterin. Montaj yuvası cihaz üzerinde kalacaksa ölçü ve geniş görüntüsü ayrıca gerekir. Numuneyi evden veya servisten göndermeden önce gerçekten hangi bölümün incelenmesi gerektiği netleştirilebilir.','İlk uyum denemesini aynı yuvada yapın','İstanbul içindeki talepte numune elinize ulaştığında hangi cihaz veya araçta deneneceği belli olmalıdır. Farklı varyantta yapılan kontrol ilk ölçüyü temsil etmeyebilir. Takılma, boşluk veya sürtme noktalarını fotoğraflayıp parça revizyonuyla birlikte paylaşın; renk ve görünüş onayını uyumdan ayrı tutabilirsiniz.','Kırık parçanın tüm parçalarını göndermeli miyim?','Küçük kopmuş bölgeler geometriyi anlamaya yardımcı olabilir. Önce fotoğrafla nelerin bulunduğunu gösterin; gönderim kapsamı ve referansların geri dönüşü görüşmede belirlenir.',['Kırık örneğin tüm görünen yüzleri','Cihazda kalan montaj yuvası','İlk numunenin deneneceği ürün varyantı'],
'İstanbul’dan gelen özel parça taleplerinde ilk ayrım, elde sağlam örnek mi kırık numune mi yoksa yalnızca montaj yuvası mı bulunduğudur. Kayıtlı çalışma yeri beyanı Ataşehir, Örnek Mahallesi’dir. İlçenizi seçmek taşıma planına yardımcı olur; her ilçede fiziksel başvuru noktası olduğu anlamına gelmez. Ön fotoğraflar, parçayı cihazdan sökmeden hangi ölçülerin gerekli olduğunu konuşmayı sağlar.',
'Küçük tırnak ve kopmuş parçaları ana numuneyle aynı kimlik altında ayrı koruyun. Montaj yerine ait fotoğrafı talebe ekleyin; örneğin geri gönderilmesi gerekiyorsa bunu belirtin. Yeni numunenin teslimi ve cihaz üzerindeki uyum kontrolü ayrı planlanır; otomatik aynı gün üretim veya kurye taahhüdü verilmez.']
};
