// Historical seed generator. Frozen v1 catalog keeps the original migration reproducible.
import { readFileSync, writeFileSync } from "node:fs";
const brands = JSON.parse(
  readFileSync(new URL("./fixtures/brand-catalog-v1.json", import.meta.url), "utf8"),
);
const literal = (value) => `'${String(value).replaceAll("'", "''")}'`;
let sql =
  "-- Generated by scripts/seed-brands.mjs. No source-company content is copied.\n";
sql +=
  "UPDATE public.tenants SET status = 'suspended' WHERE slug = 'demo' AND id = '00000000-0000-0000-0000-000000000001';\n";
for (const [i, b] of brands.entries()) {
  const id = `10000000-0000-4000-8000-00000000000${i + 1}`;
  sql += `INSERT INTO public.tenants(id,slug,name,status) VALUES('${id}',${literal(b.slug)},${literal(b.name)},'active') ON CONFLICT(slug) DO NOTHING;\n`;
  sql += `INSERT INTO public.tenant_domains(hostname,tenant_id) SELECT ${literal(b.slug + ".localhost")},id FROM public.tenants WHERE slug=${literal(b.slug)} ON CONFLICT(hostname) DO NOTHING;\n`;
  const settings = {
    services_cards: b.applications.map((title, i) => ({
      id: `s${i + 1}`,
      title_tr: title,
      desc_tr: b.featureLead,
      link: "/teklif-al",
    })),
    hero_content: {
      eyebrow_tr: b.eyebrow,
      title_tr: b.title,
      lead_tr: b.lead,
      cta_primary_tr: "Birlikte üretelim",
      cta_secondary_tr: "Neler mümkün?",
    },
    autofocus_content: { title_tr: b.featureTitle, lead_tr: b.featureLead },
    contact_info: { address_tr: "Örnek Mahallesi, İstanbul" },
    cta_content: {
      title_tr: "Bir fikrin varsa,\nbiz yanındayız.",
      lead_tr:
        "3D dosyanı yükle ya da aklındakini anlat. Gerisini birlikte şekillendirelim.",
    },
  };
  for (const [key, value] of Object.entries(settings))
    sql += `INSERT INTO public.site_settings(tenant_id,key,value) SELECT id,${literal(key)},${literal(JSON.stringify(value))}::jsonb FROM public.tenants WHERE slug=${literal(b.slug)} ON CONFLICT(tenant_id,key) DO NOTHING;\n`;
  sql += `INSERT INTO public.seo_meta(tenant_id,path,title_tr,description_tr) SELECT id,'/',${literal(b.focus + " | " + b.name)},${literal(b.description)} FROM public.tenants WHERE slug=${literal(b.slug)} ON CONFLICT(tenant_id,path) DO NOTHING;\n`;
  sql += `INSERT INTO public.tenant_features(tenant_id,feature_key,enabled) SELECT t.id,f.key,f.key IN ('blog','portfolio','faq','legal') FROM public.tenants t CROSS JOIN public.features f WHERE t.slug=${literal(b.slug)} ON CONFLICT DO NOTHING;\n`;
}
writeFileSync(
  new URL(
    "../supabase/migrations/20261001091000_four_brands.sql",
    import.meta.url,
  ),
  sql,
);
