-- Editorial landing pages. Local pages are not generated by arbitrary route substitution.
CREATE TABLE public.landing_pages (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 tenant_id uuid NOT NULL DEFAULT public.current_tenant_id() REFERENCES public.tenants(id) ON DELETE CASCADE,
 path text NOT NULL CHECK(path ~ '^/[a-z0-9/-]+$' AND path !~ '//|/$'),
 kind text NOT NULL CHECK(kind IN ('service','solution','material','guide','location')),
 title text NOT NULL, summary text NOT NULL DEFAULT '', image text NOT NULL DEFAULT '',
 sections jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(sections)='array'),
 faq jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(faq)='array'),
 status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published')),
 city text NOT NULL DEFAULT '', district text NOT NULL DEFAULT '', neighborhood text NOT NULL DEFAULT '', service text NOT NULL DEFAULT '',
 local_context text NOT NULL DEFAULT '', logistics text NOT NULL DEFAULT '', evidence text NOT NULL DEFAULT '', reviewed_at timestamptz,
 updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,path)
);
CREATE INDEX landing_pages_public ON public.landing_pages(tenant_id,status,kind);
ALTER TABLE public.landing_pages ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.landing_pages TO anon;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.landing_pages TO authenticated;
GRANT ALL ON public.landing_pages TO service_role;
CREATE POLICY "Selected brand content" ON public.landing_pages AS RESTRICTIVE FOR ALL TO anon,authenticated
 USING(tenant_id=public.current_tenant_id()) WITH CHECK(tenant_id=public.current_tenant_id());
CREATE POLICY "Published landing pages" ON public.landing_pages FOR SELECT TO anon,authenticated USING(status='published');
CREATE POLICY "Editors manage landing pages" ON public.landing_pages FOR ALL TO authenticated
 USING(public.tenant_user_has_permission(tenant_id,'seo.edit')) WITH CHECK(public.tenant_user_has_permission(tenant_id,'seo.edit'));

-- Ignore brand/place substitutions when comparing geographic copy, across all four brands.
CREATE FUNCTION public.local_content_tokens(input text) RETURNS text[] LANGUAGE sql IMMUTABLE SET search_path=public AS $$
 SELECT coalesce(array_agg(DISTINCT token),'{}') FROM regexp_split_to_table(
 regexp_replace(lower(translate(input,'İI','iı')),
 '(istanbul|örnek mahallesi|örnek|3dyanımda|3dyanimda|3dsanayi|maketyanımda|maketyanimda|parçayanımda|parcayanimda|adalar|arnavutköy|ataşehir|avcılar|bağcılar|bahçelievler|bakırköy|başakşehir|bayrampaşa|beşiktaş|beykoz|beylikdüzü|beyoğlu|büyükçekmece|çatalca|çekmeköy|esenler|esenyurt|eyüpsultan|fatih|gaziosmanpaşa|güngören|kadıköy|kağıthane|kartal|küçükçekmece|maltepe|pendik|sancaktepe|sarıyer|silivri|sultanbeyli|sultangazi|şile|şişli|tuzla|ümraniye|üsküdar|zeytinburnu)', ' ', 'g'), '[^[:alnum:]]+') token WHERE length(token)>2
$$;
CREATE FUNCTION public.local_content_similarity(a text,b text) RETURNS numeric LANGUAGE sql IMMUTABLE SET search_path=public AS $$
 WITH x AS (SELECT unnest(public.local_content_tokens(a)) t), y AS(SELECT unnest(public.local_content_tokens(b)) t)
 SELECT (SELECT count(*)::numeric FROM (SELECT t FROM x INTERSECT SELECT t FROM y) i) / greatest(1,(SELECT count(*) FROM (SELECT t FROM x UNION SELECT t FROM y) u))
$$;
CREATE FUNCTION public.validate_landing_publication() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 NEW.updated_at=now();
 IF NEW.status='published' THEN
  IF length(trim(NEW.title))<3 OR length(trim(NEW.summary))<60 OR jsonb_array_length(NEW.sections)<2
   OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.sections) s WHERE length(trim(coalesce(s->>'title','')))<3 OR length(trim(coalesce(s->>'body','')))<40)
   THEN RAISE EXCEPTION 'Başlık, açıklama ve en az iki içerik bölümünü tamamlayın.'; END IF;
  IF NEW.kind='location' THEN
   IF length(trim(NEW.local_context))<200 OR length(trim(NEW.logistics))<120 OR length(trim(NEW.evidence))<20 OR NEW.reviewed_at IS NULL OR NEW.reviewed_at>now() OR jsonb_array_length(NEW.faq)<2
    OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.faq) f WHERE length(trim(coalesce(f->>'q','')))<10 OR length(trim(coalesce(f->>'a','')))<20)
    THEN RAISE EXCEPTION 'Yerel içerik, lojistik, kaynak/teyit, kontrol tarihi ve iki yerel yanıt gerekli.'; END IF;
   -- Serialize publishes so simultaneous requests cannot evade the similarity guard.
   PERFORM pg_advisory_xact_lock(610021200);
   IF EXISTS(SELECT 1 FROM public.landing_pages p WHERE p.id<>NEW.id AND p.kind='location' AND p.status='published'
     AND public.local_content_similarity(p.local_context,NEW.local_context)>=0.80)
    THEN RAISE EXCEPTION 'Konum metni başka bir yayınla fazla benzer. Bölgeye ve müşteri ihtiyacına özgü bilgi ekleyin.'; END IF;
  END IF;
 END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.validate_landing_publication() FROM PUBLIC;
CREATE TRIGGER landing_publication_guard BEFORE INSERT OR UPDATE ON public.landing_pages FOR EACH ROW EXECUTE FUNCTION public.validate_landing_publication();
