INSERT INTO public.translations (key, namespace, tr, en) VALUES
-- Services section
('services.section.eyebrow','home','Hizmetler','Services'),
('services.section.title.pre','home','Tek atölye,','One workshop,'),
('services.section.title.em','home','uçtan uca','end-to-end'),
('services.section.title.post','home','üretim.','production.'),
('services.section.all','home','Tüm hizmetler','All services'),
('services.section.review','home','İncele','Explore'),
('services.section.s1.title','home','3D Tarama','3D Scanning'),
('services.section.s1.desc','home','Mevcut parçanın yüksek hassasiyetli dijital ikizini çıkarıyoruz. Karmaşık geometriler, organik formlar ve ölçü alınamayan parçalar için.','We capture a high-precision digital twin of the existing part. For complex geometries, organic forms and parts that cannot be measured.'),
('services.section.s2.title','home','3D Modelleme','3D Modeling'),
('services.section.s2.desc','home','Tarama verisi üzerinde mühendislik düzeltmesi, parametrik CAD modelleme ve üretim için optimize edilmiş STL hazırlığı.','Engineering corrections on scan data, parametric CAD modeling and STL preparation optimized for production.'),
('services.section.s3.title','home','3D Baskı','3D Printing'),
('services.section.s3.desc','home','FDM, SLA, SLS — parçanın kullanım amacına göre teknoloji ve malzeme seçimi, son işlem ve kalite kontrolü.','FDM, SLA, SLS — technology and material selection based on the part''s purpose, post-processing and quality control.'),
-- Process
('process.eyebrow','home','Süreç','Process'),
('process.title.pre','home','Dört adımda','Four steps,'),
('process.title.em','home','dijitalden gerçeğe','from digital to real'),
('process.lead','home','Her parça için ayrı ayrı ele alınmış, mühendislik disiplinini el emeği ile birleştiren bir üretim hattı kuruyoruz.','We build a production line that handles every part individually, blending engineering discipline with craftsmanship.'),
('process.s1.t','home','Tarama & Analiz','Scan & Analysis'),
('process.s1.d','home','Mevcut parça yüksek hassasiyetli el tipi tarayıcı ile dijitale alınır. Yıpranma, kırık ve toleranslar mühendis ekibimizce analiz edilir.','The existing part is digitized with a high-precision handheld scanner. Wear, cracks and tolerances are analyzed by our engineering team.'),
('process.s2.t','home','Mühendislik Modelleme','Engineering Modeling'),
('process.s2.d','home','Tarama nokta bulutu, parametrik CAD modeline dönüştürülür. Gerekirse iyileştirme, güçlendirme ve revizyon önerilir.','The scan point cloud is converted into a parametric CAD model. We suggest improvements, reinforcements and revisions if needed.'),
('process.s3.t','home','Baskı & Üretim','Print & Production'),
('process.s3.d','home','FDM, SLA veya SLS teknolojilerinden parçanın görevine en uygun olanı seçilir; doğru malzeme ile üretim yapılır.','We select the most suitable technology among FDM, SLA or SLS for the part''s function and produce it with the right material.'),
('process.s4.t','home','Kalite & Teslim','Quality & Delivery'),
('process.s4.d','home','Boyutsal kontrol, son işlem ve gerektiğinde montaj. Türkiye geneli kargo ile kapınıza.','Dimensional inspection, post-processing and assembly when required. Shipped across Turkey to your door.'),
-- Capabilities
('cap.eyebrow','home','Yetkinlikler','Capabilities'),
('cap.title.pre','home','Bir parçaya değil —','We don''t just look at the part —'),
('cap.title.em','home','probleme','the problem'),
('cap.title.post','home','bakıyoruz.','is what we see.'),
('cap.lead','home','Mühendislik perspektifimiz sayesinde sadece üretim değil, parçanın yıpranma sebebini de değerlendiriyor; gerekli güçlendirmeyi öneriyoruz.','Thanks to our engineering perspective we don''t just produce; we also evaluate why the part wore out and recommend the necessary reinforcement.'),
('cap.r1.k','home','Sektörler','Industries'),
('cap.r1.v','home','Otomotiv · Endüstriyel · Ev aletleri · Tarım makineleri · Mobilya aksesuarı · Mimari','Automotive · Industrial · Home appliances · Agricultural machinery · Furniture hardware · Architecture'),
('cap.r2.k','home','Teknolojiler','Technologies'),
('cap.r2.v','home','FDM · SLA · MSLA · SLS · Çoklu malzeme baskı','FDM · SLA · MSLA · SLS · Multi-material printing'),
('cap.r3.k','home','Malzemeler','Materials'),
('cap.r3.v','home','PLA · PETG · ABS · ASA · PA12 (Naylon) · TPU · PC · Reçine (sert / esnek / mühendislik)','PLA · PETG · ABS · ASA · PA12 (Nylon) · TPU · PC · Resin (rigid / flexible / engineering)'),
('cap.r4.k','home','Tarama','Scanning'),
('cap.r4.v','home','El tipi yapılandırılmış ışık · Mavi LED · ±0.02 mm hassasiyet','Handheld structured light · Blue LED · ±0.02 mm precision'),
('cap.r5.k','home','Modelleme','Modeling'),
('cap.r5.v','home','Reverse engineering · Parametrik CAD · Topology iyileştirme · STL onarım','Reverse engineering · Parametric CAD · Topology optimization · STL repair'),
('cap.r6.k','home','Son işlem','Post-processing'),
('cap.r6.v','home','Zımpara · Astar / boya · Yapıştırma · Diş açma · Montaj','Sanding · Primer / paint · Bonding · Threading · Assembly'),
('cap.r7.k','home','Teslim süresi','Lead time'),
('cap.r7.v','home','Standart 2–7 gün · Acil prototip 24–48 saat','Standard 2–7 days · Rush prototype 24–48 hours'),
-- AutoFocus
('autofocus.eyebrow','home','Uzmanlık · Otomotiv','Expertise · Automotive'),
('autofocus.title.pre','home','Oto yedek parçada','No more waiting'),
('autofocus.title.em','home','artık','for'),
('autofocus.title.post','home','bekleme yok.','auto spare parts.'),
('autofocus.lead','home','Türkiye''de bulunamayan, üretimi durmuş ya da yurt dışından beklenen oto yedek parçaları <s>3 boyutlu olarak yeniden üretiyoruz.</s> Mevcut bir parçayı tarıyor, mühendislik düzeltmesini yapıyor ve kullanıma uygun malzeme ile basıyoruz.','We <s>re-manufacture in 3D</s> the auto spare parts that are unavailable in Turkey, out of production, or awaited from abroad. We scan the existing part, apply engineering corrections and print it in a fit-for-purpose material.'),
('autofocus.p1','home','Üretimi durmuş klasik araç parçaları','Discontinued classic-car parts'),
('autofocus.p2','home','Bulunamayan iç-dış trim parçaları','Hard-to-find interior/exterior trim'),
('autofocus.p3','home','Kırık tutucu, klips, braket ve aparatlar','Broken holders, clips, brackets and fixtures'),
('autofocus.p4','home','Motor odası — emme, kapak, mahfaza parçaları','Engine bay — intake, cover and housing parts'),
('autofocus.p5','home','Saç, plastik, kompozit eşdeğer üretim','Sheet, plastic, composite equivalent production'),
('autofocus.cta','home','Detaylı bilgi & örnek vakalar','Details & case studies'),
('autofocus.image.alt','home','3D baskı ile yeniden üretilmiş klasik araç yedek parçaları','Classic-car spare parts re-manufactured via 3D printing'),
('autofocus.case.eyebrow','home','Vaka','Case'),
('autofocus.case.title','home','1972 model kapı kolu — 3 günde teslim','1972 door handle — delivered in 3 days'),
-- Testimonials
('testi.eyebrow','home','Referanslar','Testimonials'),
('testi.title','home','Sözümüzü tutuyoruz.','We keep our promise.'),
('testi.t1.q','home','1968 model aracımın iç döşeme klipsi yıllardır bulunamıyordu. 4 günde hem orijinaline tıpatıp hem daha dayanıklı olarak teslim aldım.','The interior trim clip for my 1968 car had been unavailable for years. In 4 days I got it back — identical to the original and more durable.'),
('testi.t1.n','home','Erkan T.','Erkan T.'),
('testi.t1.r','home','Klasik araç koleksiyoneri','Classic-car collector'),
('testi.t2.q','home','Endüstriyel makinemizin Almanya''dan beklediğimiz parçası 6 hafta sonra gelecekti. 3D Yanında 48 saatte üretti, üretim hattımız durmadı.','The part we were waiting on from Germany would arrive in 6 weeks. 3D Yanında produced it in 48 hours and our line never stopped.'),
('testi.t2.n','home','Mert D.','Mert D.'),
('testi.t2.r','home','Üretim Müdürü, Bursa','Production Manager, Bursa'),
('testi.t3.q','home','Prototip aşamasında üç farklı revizyonu hızlıca aldık. Mühendislik geri dönüşleri çok değerliydi.','During prototyping we received three different revisions quickly. The engineering feedback was invaluable.'),
('testi.t3.n','home','Ayşe K.','Ayşe K.'),
('testi.t3.r','home','Ürün Tasarımcısı','Product Designer'),
-- Mobile sticky CTA
('mobileCta.aria','common','Hızlı iletişim','Quick contact'),
('mobileCta.callAria','common','Telefonla ara','Call by phone'),
('mobileCta.call','common','Ara','Call'),
('mobileCta.waAria','common','WhatsApp''tan yaz','Message on WhatsApp'),
('mobileCta.wa','common','WhatsApp','WhatsApp'),
-- FAQ
('faq.eyebrow','common','FAQ','FAQ'),
('faq.title','common','Sık sorulan sorular','Frequently asked questions'),
('faq.lead','common','Aklınıza takılan başka bir şey varsa bize yazın — 24 saat içinde dönelim.','If there''s something else on your mind, write to us — we''ll reply within 24 hours.')
ON CONFLICT (key) DO UPDATE SET
  tr = EXCLUDED.tr,
  en = EXCLUDED.en,
  namespace = EXCLUDED.namespace,
  updated_at = now();